create extension if not exists unaccent;

create or replace function public.slugify(value text)
returns text
language sql
immutable strict
as $function$
	with unaccented as (
		select unaccent(value) as value
	),
	lowercase as (
		select lower(value) as value
		from unaccented
	),
	removed_quotes as (
		select regexp_replace(value, '[''"]+', '', 'gi') as value
		from lowercase
	),
	hyphenated as (
		select regexp_replace(value, '[^a-z0-9\\-_]+', '-', 'gi') as value
		from removed_quotes
	),
	trimmed as (
		select regexp_replace(regexp_replace(value, '\\-+$', ''), '^\\-', '') as value
		from hyphenated
	)
	select value from trimmed;
$function$;

create table public.vendor_submissions (
	id bigint generated by default as identity primary key,
	submission_id bigint not null unique references public.submissions(id) on update cascade on delete cascade,
	target_vendor_id bigint references public.vendors(id) on update cascade on delete cascade,
	name text not null,
	base_url text not null check (base_url ~ '^https?://'),
	country_iso text not null check (country_iso ~ '^[A-Z]{2}$'),
	currency text not null check (currency ~ '^[A-Z]{3}$'),
	logo_url text,
	created_at timestamp with time zone not null default now()
);

alter table public.vendor_submissions enable row level security;

create policy "Users can see their own vendor submissions"
on public.vendor_submissions
as permissive
for select
to authenticated
using (
	exists (
		select 1
		from public.submissions
		where submissions.id = vendor_submissions.submission_id
			and submissions.submitted_by_id = auth.uid()
	)
);

create policy "Admin and Database Manager can see all vendor submissions"
on public.vendor_submissions
as permissive
for select
to authenticated
using (public.is_database_manager());

create or replace function public.submit_vendor(
	p_operation public.submission_operation,
	p_submitter_note text default null,
	p_vendor jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
	v_user_id uuid := auth.uid();
	v_submission_id bigint;
	v_vendor record;
begin
	if v_user_id is null then
		raise exception 'Authentication required' using errcode = '42501';
	end if;

	select *
	into v_vendor
	from jsonb_to_record(p_vendor) as vendor_data (
		target_vendor_id bigint,
		name text,
		base_url text,
		country_iso text,
		currency text,
		logo_url text
	);

	if p_operation = 'create'::public.submission_operation
		and v_vendor.target_vendor_id is not null then
		raise exception 'Create submissions cannot target an existing vendor' using errcode = '22023';
	elsif p_operation = 'update'::public.submission_operation
		and v_vendor.target_vendor_id is null then
		raise exception 'Update submissions require target_vendor_id' using errcode = '22023';
	end if;

	insert into public.submissions (
		type,
		status,
		submitter_note,
		submitted_by_id,
		operation
	)
	values (
		'vendor'::public.submission_type,
		'Pending'::public.submission_status,
		p_submitter_note,
		v_user_id,
		p_operation
	)
	returning id into v_submission_id;

	insert into public.vendor_submissions (
		submission_id,
		target_vendor_id,
		name,
		base_url,
		country_iso,
		currency,
		logo_url
	)
	values (
		v_submission_id,
		v_vendor.target_vendor_id,
		v_vendor.name,
		v_vendor.base_url,
		v_vendor.country_iso,
		v_vendor.currency,
		v_vendor.logo_url
	);

	return v_submission_id;
end;
$function$;

create or replace function public.copy_cube_submission(
	p_submission_id bigint,
	p_reviewer_id uuid
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
	v_submission public.submissions%rowtype;
	v_cube_submission public.cube_submissions%rowtype;
	v_cube_id bigint;
	v_brand_id bigint;
	v_type_id bigint;
	v_series_id bigint;
	v_related_to_slug text;
	v_slug_base text;
	v_slug text;
	v_slug_suffix integer := 0;
begin
	select *
	into v_submission
	from public.submissions
	where id = p_submission_id
		and type = 'cube'::public.submission_type;

	if not found then
		raise exception 'Cube submission % does not exist', p_submission_id using errcode = 'P0002';
	end if;

	select *
	into v_cube_submission
	from public.cube_submissions
	where submission_id = p_submission_id;

	if not found then
		raise exception 'Cube submission data is missing for submission %', p_submission_id using errcode = 'P0002';
	end if;

	if v_cube_submission.proposed_brand_name is not null then
		insert into public.brands (name, added_by_id)
		values (v_cube_submission.proposed_brand_name, v_submission.submitted_by_id)
		on conflict (name) do update set name = excluded.name
		returning id into v_brand_id;
	else
		v_brand_id := v_cube_submission.brand_id;
	end if;

	if v_brand_id is null then
		raise exception 'Cube submission must specify a brand' using errcode = '22023';
	end if;

	if v_cube_submission.proposed_type_name is not null then
		insert into public.cube_types (name, added_by_id)
		values (v_cube_submission.proposed_type_name, v_submission.submitted_by_id)
		on conflict (name) do update set name = excluded.name
		returning id into v_type_id;
	else
		v_type_id := v_cube_submission.type_id;
	end if;

	if v_type_id is null then
		raise exception 'Cube submission must specify a type' using errcode = '22023';
	end if;

	if v_cube_submission.proposed_series_name is not null then
		insert into public.cube_series (name)
		values (v_cube_submission.proposed_series_name)
		on conflict (name) do update set name = excluded.name
		returning id into v_series_id;
	else
		v_series_id := v_cube_submission.series_id;
	end if;

	if v_cube_submission.related_to_id is not null then
		select slug
		into v_related_to_slug
		from public.cube_models
		where id = v_cube_submission.related_to_id;

		if not found then
			raise exception 'Related cube % does not exist', v_cube_submission.related_to_id using errcode = '22023';
		end if;
	end if;

	if v_submission.operation = 'create'::public.submission_operation then
		if v_cube_submission.target_cube_id is not null then
			raise exception 'Create submissions cannot target an existing cube' using errcode = '22023';
		end if;

		v_slug_base := public.slugify(v_cube_submission.name);
		if v_slug_base = '' then
			raise exception 'Cube name cannot produce a valid slug' using errcode = '22023';
		end if;

		perform pg_advisory_xact_lock(hashtext(v_slug_base));
		v_slug := v_slug_base;
		while exists (select 1 from public.cube_models where slug = v_slug) loop
			v_slug_suffix := v_slug_suffix + 1;
			v_slug := v_slug_base || '-' || v_slug_suffix;
		end loop;

		insert into public.cube_models (
			brand_id,
			name,
			image_url,
			related_to,
			related_to_id,
			release_date,
			release_date_precision,
			series_id,
			size,
			slug,
			sub_type,
			submitted_by_id,
			surface_finish,
			type_id,
			verified_at,
			verified_by_id,
			version_type,
			weight,
			discontinued
		)
		values (
			v_brand_id,
			v_cube_submission.name,
			v_cube_submission.image_url,
			v_related_to_slug,
			v_cube_submission.related_to_id,
			v_cube_submission.release_date,
			v_cube_submission.release_date_precision,
			v_series_id,
			v_cube_submission.size,
			v_slug,
			v_cube_submission.sub_type,
			v_submission.submitted_by_id,
			v_cube_submission.surface_finish,
			v_type_id,
			now(),
			p_reviewer_id,
			v_cube_submission.version_type,
			v_cube_submission.weight,
			v_cube_submission.discontinued
		)
		returning id into v_cube_id;
	elsif v_submission.operation = 'update'::public.submission_operation then
		if v_cube_submission.target_cube_id is null then
			raise exception 'Update submissions require a target cube' using errcode = '22023';
		end if;

		update public.cube_models
		set
			brand_id = v_brand_id,
			name = v_cube_submission.name,
			image_url = v_cube_submission.image_url,
			related_to = v_related_to_slug,
			related_to_id = v_cube_submission.related_to_id,
			release_date = v_cube_submission.release_date,
			release_date_precision = v_cube_submission.release_date_precision,
			series_id = v_series_id,
			size = v_cube_submission.size,
			sub_type = v_cube_submission.sub_type,
			surface_finish = v_cube_submission.surface_finish,
			type_id = v_type_id,
			verified_at = now(),
			verified_by_id = p_reviewer_id,
			version_type = v_cube_submission.version_type,
			weight = v_cube_submission.weight,
			discontinued = v_cube_submission.discontinued
		where id = v_cube_submission.target_cube_id
		returning id into v_cube_id;

		if not found then
			raise exception 'Target cube % does not exist', v_cube_submission.target_cube_id using errcode = 'P0002';
		end if;
	else
		raise exception 'Unsupported submission operation: %', v_submission.operation using errcode = '22023';
	end if;

	delete from public.cubes_model_features
	where cube = (select slug from public.cube_models where id = v_cube_id);

	insert into public.cubes_model_features (cube, feature)
	select cube.slug, feature.code
	from public.cube_models cube
	cross join public.cube_submission_features submission_feature
	join public.cube_features feature on feature.id = submission_feature.feature_id
	where cube.id = v_cube_id
		and submission_feature.cube_submission_id = v_cube_submission.id;

	delete from public.cube_vendor_links
	where cube_id = v_cube_id;

	insert into public.cube_vendor_links (cube_id, vendor_id, url, price, available)
	select v_cube_id, vendor_id, url, price, available
	from public.cube_vendor_link_submissions
	where cube_submission_id = v_cube_submission.id;
end;
$function$;

create or replace function public.copy_vendor_submission(
	p_submission_id bigint
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
	v_submission public.submissions%rowtype;
	v_vendor_submission public.vendor_submissions%rowtype;
	v_slug_base text;
	v_slug text;
	v_slug_suffix integer := 0;
begin
	select *
	into v_submission
	from public.submissions
	where id = p_submission_id
		and type = 'vendor'::public.submission_type;

	if not found then
		raise exception 'Vendor submission % does not exist', p_submission_id using errcode = 'P0002';
	end if;

	select *
	into v_vendor_submission
	from public.vendor_submissions
	where submission_id = p_submission_id;

	if not found then
		raise exception 'Vendor submission data is missing for submission %', p_submission_id using errcode = 'P0002';
	end if;

	if v_submission.operation = 'create'::public.submission_operation then
		if v_vendor_submission.target_vendor_id is not null then
			raise exception 'Create submissions cannot target an existing vendor' using errcode = '22023';
		end if;

		v_slug_base := public.slugify(v_vendor_submission.name);
		if v_slug_base = '' then
			raise exception 'Vendor name cannot produce a valid slug' using errcode = '22023';
		end if;

		perform pg_advisory_xact_lock(hashtext(v_slug_base));
		v_slug := v_slug_base;
		while exists (select 1 from public.vendors where slug = v_slug) loop
			v_slug_suffix := v_slug_suffix + 1;
			v_slug := v_slug_base || '-' || v_slug_suffix;
		end loop;

		insert into public.vendors (
			name,
			slug,
			base_url,
			country_iso,
			currency,
			logo_url,
			verified
		)
		values (
			v_vendor_submission.name,
			v_slug,
			v_vendor_submission.base_url,
			v_vendor_submission.country_iso,
			v_vendor_submission.currency,
			v_vendor_submission.logo_url,
			true
		);
	elsif v_submission.operation = 'update'::public.submission_operation then
		if v_vendor_submission.target_vendor_id is null then
			raise exception 'Update submissions require a target vendor' using errcode = '22023';
		end if;

		update public.vendors
		set
			name = v_vendor_submission.name,
			base_url = v_vendor_submission.base_url,
			country_iso = v_vendor_submission.country_iso,
			currency = v_vendor_submission.currency,
			logo_url = v_vendor_submission.logo_url,
			verified = true
		where id = v_vendor_submission.target_vendor_id;

		if not found then
			raise exception 'Target vendor % does not exist', v_vendor_submission.target_vendor_id using errcode = 'P0002';
		end if;
	else
		raise exception 'Unsupported submission operation: %', v_submission.operation using errcode = '22023';
	end if;
end;
$function$;

create or replace function public.approve_submission(p_submission_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
	v_reviewer_id uuid := auth.uid();
	v_submission public.submissions%rowtype;
begin
	if v_reviewer_id is null then
		raise exception 'Authentication required' using errcode = '42501';
	end if;

	if not public.is_database_manager() then
		raise exception 'Database manager role required' using errcode = '42501';
	end if;

	select *
	into v_submission
	from public.submissions
	where id = p_submission_id
	for update;

	if not found then
		raise exception 'Submission % does not exist', p_submission_id using errcode = 'P0002';
	end if;

	if v_submission.status <> 'Pending'::public.submission_status then
		raise exception 'Only pending submissions can be approved' using errcode = '22023';
	end if;

	case v_submission.type
		when 'cube'::public.submission_type then
			perform public.copy_cube_submission(p_submission_id, v_reviewer_id);
		when 'vendor'::public.submission_type then
			perform public.copy_vendor_submission(p_submission_id);
		else
			raise exception 'Unsupported submission type: %', v_submission.type using errcode = '22023';
	end case;

	update public.submissions
	set
		status = 'Approved'::public.submission_status,
		reviewed_by_id = v_reviewer_id,
		reviewed_at = now()
	where id = p_submission_id;
end;
$function$;

revoke all on function public.submit_vendor(public.submission_operation, text, jsonb) from public;
grant execute on function public.submit_vendor(public.submission_operation, text, jsonb) to authenticated;

revoke all on function public.copy_cube_submission(bigint, uuid) from public;
revoke all on function public.copy_vendor_submission(bigint) from public;

revoke all on function public.approve_submission(bigint) from public;
grant execute on function public.approve_submission(bigint) to authenticated;
