[build]
  publish = "build"
  command = "pnpm run build"

[[_redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/server"
  status = 200

[[_redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''