create type "public"."submission_operation" as enum ('create', 'update');

create type "public"."submission_type" as enum ('cube', 'vendor');

  create table "public"."cube_submission_features" (
    "id" bigint generated by default as identity not null,
    "cube_submission_id" bigint not null,
    "feature_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."cube_submission_features" enable row level security;


  create table "public"."cube_submissions" (
    "id" bigint generated by default as identity not null,
    "submission_id" bigint not null,
    "target_cube_id" bigint,
    "name" text not null,
    "version_type" public.cube_version_type not null,
    "image_url" text not null,
    "brand_id" bigint,
    "proposed_brand_name" text,
    "type_id" bigint,
    "proposed_type_name" text,
    "series_id" bigint,
    "proposed_series_name" text,
    "related_to_id" bigint,
    "release_date" date,
    "release_date_precision" public.date_precision,
    "weight" numeric,
    "size" text,
    "surface_finish" public.cube_surface_finish,
    "discontinued" boolean not null,
    "created_at" timestamp with time zone not null default now(),
    "sub_type" public.cubes_subtypes not null
      );


alter table "public"."cube_submissions" enable row level security;


  create table "public"."cube_vendor_link_submissions" (
    "id" bigint generated by default as identity not null,
    "cube_submission_id" bigint not null,
    "vendor_id" bigint not null,
    "url" text not null,
    "price" numeric not null,
    "available" boolean not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."cube_vendor_link_submissions" enable row level security;


  create table "public"."submissions" (
    "id" bigint generated by default as identity not null,
    "type" public.submission_type not null,
    "status" public.submission_status not null default 'Pending'::public.submission_status,
    "submitter_note" text,
    "reviewer_note" text,
    "reviewed_by_id" uuid,
    "submitted_by_id" uuid not null default auth.uid(),
    "reviewed_at" timestamp with time zone,
    "submitted_at" timestamp with time zone not null default now(),
    "operation" public.submission_operation not null
      );


alter table "public"."submissions" enable row level security;

CREATE UNIQUE INDEX cube_submission_features_pkey ON public.cube_submission_features USING btree (id);

CREATE UNIQUE INDEX cube_submission_id_feature_id_unique ON public.cube_submission_features USING btree (cube_submission_id, feature_id);

CREATE UNIQUE INDEX cube_submissions_pkey ON public.cube_submissions USING btree (id);

CREATE UNIQUE INDEX cube_vendor_link_submissions_pkey ON public.cube_vendor_link_submissions USING btree (id);

CREATE UNIQUE INDEX submissions_pkey ON public.submissions USING btree (id);

alter table "public"."cube_submission_features" add constraint "cube_submission_features_pkey" PRIMARY KEY using index "cube_submission_features_pkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_pkey" PRIMARY KEY using index "cube_submissions_pkey";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_pkey" PRIMARY KEY using index "cube_vendor_link_submissions_pkey";

alter table "public"."submissions" add constraint "submissions_pkey" PRIMARY KEY using index "submissions_pkey";

alter table "public"."cube_submission_features" add constraint "cube_submission_features_cube_submission_id_fkey" FOREIGN KEY (cube_submission_id) REFERENCES public.cube_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submission_features" validate constraint "cube_submission_features_cube_submission_id_fkey";

alter table "public"."cube_submission_features" add constraint "cube_submission_features_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES public.cube_features(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submission_features" validate constraint "cube_submission_features_feature_id_fkey";

alter table "public"."cube_submission_features" add constraint "cube_submission_id_feature_id_unique" UNIQUE using index "cube_submission_id_feature_id_unique";

alter table "public"."cube_submissions" add constraint "cube_submissions_brand_check" CHECK (((brand_id IS NOT NULL) <> (proposed_brand_name IS NOT NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_brand_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_brand_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_related_to_id_fkey" FOREIGN KEY (related_to_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_related_to_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_release_date_complete_check" CHECK (((release_date IS NULL) = (release_date_precision IS NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_release_date_complete_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_series_check" CHECK (((series_id IS NULL) OR (proposed_series_name IS NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_series_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_series_id_fkey" FOREIGN KEY (series_id) REFERENCES public.cube_series(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_series_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_size_check" CHECK ((size ~ '^[0-9]+(\.[0-9]+)?\sx\s[0-9]+(\.[0-9]+)?\sx\s[0-9]+(\.[0-9]+)?$'::text)) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_size_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_submission_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_target_cube_id_fkey" FOREIGN KEY (target_cube_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_target_cube_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_type_check" CHECK (((type_id IS NOT NULL) <> (proposed_type_name IS NOT NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_type_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_type_id_fkey" FOREIGN KEY (type_id) REFERENCES public.cube_types(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_type_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_weight_check" CHECK ((weight > (0)::numeric)) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_weight_check";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_cube_submission_id_fkey" FOREIGN KEY (cube_submission_id) REFERENCES public.cube_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_vendor_link_submissions" validate constraint "cube_vendor_link_submissions_cube_submission_id_fkey";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_vendor_link_submissions" validate constraint "cube_vendor_link_submissions_vendor_id_fkey";

alter table "public"."submissions" add constraint "submissions_reviewed_by_id_fkey" FOREIGN KEY (reviewed_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."submissions" validate constraint "submissions_reviewed_by_id_fkey";

alter table "public"."submissions" add constraint "submissions_submitted_by_id_fkey" FOREIGN KEY (submitted_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."submissions" validate constraint "submissions_submitted_by_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.submit_cube(p_operation public.submission_operation, p_submitter_note text DEFAULT NULL::text, p_cube jsonb DEFAULT '{}'::jsonb, p_feature_ids bigint[] DEFAULT '{}'::bigint[], p_vendor_links jsonb DEFAULT '[]'::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare v_user_id uuid := auth.uid();
v_submission_id bigint;
v_cube_submission_id bigint;
v_cube record;
v_vendor_link jsonb;
begin if v_user_id is null then raise exception 'Authentication required' using errcode = '42501';
end if;
select * into v_cube
from jsonb_to_record(p_cube) as cube_data (
        target_cube_id bigint,
        name text,
        version_type public.cube_version_type,
        image_url text,
        brand_id bigint,
        proposed_brand_name text,
        type_id bigint,
        proposed_type_name text,
        series_id bigint,
        proposed_series_name text,
        related_to_id bigint,
        release_date date,
        release_date_precision public.date_precision,
        sub_type public.cubes_subtypes,
        weight numeric,
        size text,
        surface_finish public.cube_surface_finish,
        discontinued boolean
    );
if p_operation = 'create'::public.submission_operation
and v_cube.target_cube_id is not null then raise exception 'Create submissions cannot target an existing cube' using errcode = '22023';
elsif p_operation = 'update'::public.submission_operation
and v_cube.target_cube_id is null then raise exception 'Update submissions require target_cube_id' using errcode = '22023';
end if;
insert into public.submissions (
        type,
        status,
        submitter_note,
        submitted_by_id,
        operation
    )
values (
        'cube'::public.submission_type,
        'Pending'::public.submission_status,
        p_submitter_note,
        v_user_id,
        p_operation
    )
returning id into v_submission_id;
insert into public.cube_submissions (
        submission_id,
        target_cube_id,
        name,
        version_type,
        image_url,
        brand_id,
        proposed_brand_name,
        type_id,
        proposed_type_name,
        series_id,
        proposed_series_name,
        related_to_id,
        release_date,
        release_date_precision,
        sub_type,
        weight,
        size,
        surface_finish,
        discontinued
    )
values (
        v_submission_id,
        v_cube.target_cube_id,
        v_cube.name,
        v_cube.version_type,
        v_cube.image_url,
        v_cube.brand_id,
        v_cube.proposed_brand_name,
        v_cube.type_id,
        v_cube.proposed_type_name,
        v_cube.series_id,
        v_cube.proposed_series_name,
        v_cube.related_to_id,
        v_cube.release_date,
        v_cube.release_date_precision,
        v_cube.sub_type,
        v_cube.weight,
        v_cube.size,
        v_cube.surface_finish,
        v_cube.discontinued
    )
returning id into v_cube_submission_id;
insert into public.cube_submission_features (cube_submission_id, feature_id)
select v_cube_submission_id,
    proposed.feature_id
from (
        select distinct feature_id
        from unnest(p_feature_ids) as values_list(feature_id)
        where feature_id is not null
    ) proposed;
for v_vendor_link in
select value
from jsonb_array_elements(p_vendor_links) loop
insert into public.cube_vendor_link_submissions (
        cube_submission_id,
        vendor_id,
        url,
        price,
        available
    )
values (
        v_cube_submission_id,
        (v_vendor_link->>'vendor_id')::bigint,
        (v_vendor_link->>'url')::text,
        (v_vendor_link->>'price')::numeric,
        (v_vendor_link->>'available')::boolean
    );
end loop;
return v_submission_id;
end;
$function$
;

grant delete on table "public"."cube_submission_features" to "anon";

grant insert on table "public"."cube_submission_features" to "anon";

grant references on table "public"."cube_submission_features" to "anon";

grant select on table "public"."cube_submission_features" to "anon";

grant trigger on table "public"."cube_submission_features" to "anon";

grant truncate on table "public"."cube_submission_features" to "anon";

grant update on table "public"."cube_submission_features" to "anon";

grant delete on table "public"."cube_submission_features" to "authenticated";

grant insert on table "public"."cube_submission_features" to "authenticated";

grant references on table "public"."cube_submission_features" to "authenticated";

grant select on table "public"."cube_submission_features" to "authenticated";

grant trigger on table "public"."cube_submission_features" to "authenticated";

grant truncate on table "public"."cube_submission_features" to "authenticated";

grant update on table "public"."cube_submission_features" to "authenticated";

grant delete on table "public"."cube_submission_features" to "service_role";

grant insert on table "public"."cube_submission_features" to "service_role";

grant references on table "public"."cube_submission_features" to "service_role";

grant select on table "public"."cube_submission_features" to "service_role";

grant trigger on table "public"."cube_submission_features" to "service_role";

grant truncate on table "public"."cube_submission_features" to "service_role";

grant update on table "public"."cube_submission_features" to "service_role";

grant delete on table "public"."cube_submissions" to "anon";

grant insert on table "public"."cube_submissions" to "anon";

grant references on table "public"."cube_submissions" to "anon";

grant select on table "public"."cube_submissions" to "anon";

grant trigger on table "public"."cube_submissions" to "anon";

grant truncate on table "public"."cube_submissions" to "anon";

grant update on table "public"."cube_submissions" to "anon";

grant delete on table "public"."cube_submissions" to "authenticated";

grant insert on table "public"."cube_submissions" to "authenticated";

grant references on table "public"."cube_submissions" to "authenticated";

grant select on table "public"."cube_submissions" to "authenticated";

grant trigger on table "public"."cube_submissions" to "authenticated";

grant truncate on table "public"."cube_submissions" to "authenticated";

grant update on table "public"."cube_submissions" to "authenticated";

grant delete on table "public"."cube_submissions" to "service_role";

grant insert on table "public"."cube_submissions" to "service_role";

grant references on table "public"."cube_submissions" to "service_role";

grant select on table "public"."cube_submissions" to "service_role";

grant trigger on table "public"."cube_submissions" to "service_role";

grant truncate on table "public"."cube_submissions" to "service_role";

grant update on table "public"."cube_submissions" to "service_role";

grant delete on table "public"."cube_vendor_link_submissions" to "anon";

grant insert on table "public"."cube_vendor_link_submissions" to "anon";

grant references on table "public"."cube_vendor_link_submissions" to "anon";

grant select on table "public"."cube_vendor_link_submissions" to "anon";

grant trigger on table "public"."cube_vendor_link_submissions" to "anon";

grant truncate on table "public"."cube_vendor_link_submissions" to "anon";

grant update on table "public"."cube_vendor_link_submissions" to "anon";

grant delete on table "public"."cube_vendor_link_submissions" to "authenticated";

grant insert on table "public"."cube_vendor_link_submissions" to "authenticated";

grant references on table "public"."cube_vendor_link_submissions" to "authenticated";

grant select on table "public"."cube_vendor_link_submissions" to "authenticated";

grant trigger on table "public"."cube_vendor_link_submissions" to "authenticated";

grant truncate on table "public"."cube_vendor_link_submissions" to "authenticated";

grant update on table "public"."cube_vendor_link_submissions" to "authenticated";

grant delete on table "public"."cube_vendor_link_submissions" to "service_role";

grant insert on table "public"."cube_vendor_link_submissions" to "service_role";

grant references on table "public"."cube_vendor_link_submissions" to "service_role";

grant select on table "public"."cube_vendor_link_submissions" to "service_role";

grant trigger on table "public"."cube_vendor_link_submissions" to "service_role";

grant truncate on table "public"."cube_vendor_link_submissions" to "service_role";

grant update on table "public"."cube_vendor_link_submissions" to "service_role";

grant delete on table "public"."submissions" to "anon";

grant insert on table "public"."submissions" to "anon";

grant references on table "public"."submissions" to "anon";

grant select on table "public"."submissions" to "anon";

grant trigger on table "public"."submissions" to "anon";

grant truncate on table "public"."submissions" to "anon";

grant update on table "public"."submissions" to "anon";

grant delete on table "public"."submissions" to "authenticated";

grant insert on table "public"."submissions" to "authenticated";

grant references on table "public"."submissions" to "authenticated";

grant select on table "public"."submissions" to "authenticated";

grant trigger on table "public"."submissions" to "authenticated";

grant truncate on table "public"."submissions" to "authenticated";

grant update on table "public"."submissions" to "authenticated";

grant delete on table "public"."submissions" to "service_role";

grant insert on table "public"."submissions" to "service_role";

grant references on table "public"."submissions" to "service_role";

grant select on table "public"."submissions" to "service_role";

grant trigger on table "public"."submissions" to "service_role";

grant truncate on table "public"."submissions" to "service_role";

grant update on table "public"."submissions" to "service_role";


  create policy "Enable read access for all users"
  on "public"."cube_series"
  as permissive
  for select
  to public
using (true);



  create policy "Users can only see their submissions"
  on "public"."cube_submission_features"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.cube_submissions cs
     JOIN public.submissions s ON ((s.id = cs.submission_id)))
  WHERE ((cs.id = cube_submission_features.cube_submission_id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Admin and Database Managers can see all rows"
  on "public"."cube_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.user_id = ( SELECT auth.uid() AS uid)) AND (p.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Users can see their own submissions"
  on "public"."cube_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.submissions s
  WHERE ((cube_submissions.submission_id = s.id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Users can only see their submissions"
  on "public"."cube_vendor_link_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.cube_submissions cs
     JOIN public.submissions s ON ((s.id = cs.submission_id)))
  WHERE ((cube_vendor_link_submissions.cube_submission_id = cs.id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Admins and Database Managers can select submissions"
  on "public"."submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Users can only see their own submissions"
  on "public"."submissions"
  as permissive
  for select
  to authenticated
using ((submitted_by_id = auth.uid()));
