drop trigger if exists "trg_helpful_rating_table_rule" on "public"."helpful_rating";

drop policy "Enable delete for users based on username" on "public"."helpful_rating";

drop policy "Enable insert for authenticated users only" on "public"."helpful_rating";

drop policy "Enable read access for all users" on "public"."helpful_rating";

revoke delete on table "public"."helpful_rating" from "anon";

revoke insert on table "public"."helpful_rating" from "anon";

revoke references on table "public"."helpful_rating" from "anon";

revoke select on table "public"."helpful_rating" from "anon";

revoke trigger on table "public"."helpful_rating" from "anon";

revoke truncate on table "public"."helpful_rating" from "anon";

revoke update on table "public"."helpful_rating" from "anon";

revoke delete on table "public"."helpful_rating" from "authenticated";

revoke insert on table "public"."helpful_rating" from "authenticated";

revoke references on table "public"."helpful_rating" from "authenticated";

revoke select on table "public"."helpful_rating" from "authenticated";

revoke trigger on table "public"."helpful_rating" from "authenticated";

revoke truncate on table "public"."helpful_rating" from "authenticated";

revoke update on table "public"."helpful_rating" from "authenticated";

revoke delete on table "public"."helpful_rating" from "service_role";

revoke insert on table "public"."helpful_rating" from "service_role";

revoke references on table "public"."helpful_rating" from "service_role";

revoke select on table "public"."helpful_rating" from "service_role";

revoke trigger on table "public"."helpful_rating" from "service_role";

revoke truncate on table "public"."helpful_rating" from "service_role";

revoke update on table "public"."helpful_rating" from "service_role";

alter table "public"."helpful_rating" drop constraint "helpful_rating_user_id_fkey";

drop function if exists "public"."helpful_rating_table_rules"();

alter table "public"."helpful_rating" drop constraint "helpful_rating_pkey";

drop index if exists "public"."helpful_rating_pkey";

drop table "public"."helpful_rating";


  create table "public"."helpful_cube_rating" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "rating_id" bigint not null,
    "user_id" uuid not null
      );


alter table "public"."helpful_cube_rating" enable row level security;

drop type "public"."rating_categories";

CREATE UNIQUE INDEX helpful_cube_rating_rating_id_user_id_unique ON public.helpful_cube_rating USING btree (rating_id, user_id);

CREATE UNIQUE INDEX helpful_rating_pkey ON public.helpful_cube_rating USING btree (id);

alter table "public"."helpful_cube_rating" add constraint "helpful_rating_pkey" PRIMARY KEY using index "helpful_rating_pkey";

alter table "public"."helpful_cube_rating" add constraint "helpful_cube_rating_rating_id_fkey" FOREIGN KEY (rating_id) REFERENCES public.user_cube_ratings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."helpful_cube_rating" validate constraint "helpful_cube_rating_rating_id_fkey";

alter table "public"."helpful_cube_rating" add constraint "helpful_cube_rating_rating_id_user_id_unique" UNIQUE using index "helpful_cube_rating_rating_id_user_id_unique";

alter table "public"."helpful_cube_rating" add constraint "helpful_rating_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."helpful_cube_rating" validate constraint "helpful_rating_user_id_fkey";

grant delete on table "public"."helpful_cube_rating" to "anon";

grant insert on table "public"."helpful_cube_rating" to "anon";

grant references on table "public"."helpful_cube_rating" to "anon";

grant select on table "public"."helpful_cube_rating" to "anon";

grant trigger on table "public"."helpful_cube_rating" to "anon";

grant truncate on table "public"."helpful_cube_rating" to "anon";

grant update on table "public"."helpful_cube_rating" to "anon";

grant delete on table "public"."helpful_cube_rating" to "authenticated";

grant insert on table "public"."helpful_cube_rating" to "authenticated";

grant references on table "public"."helpful_cube_rating" to "authenticated";

grant select on table "public"."helpful_cube_rating" to "authenticated";

grant trigger on table "public"."helpful_cube_rating" to "authenticated";

grant truncate on table "public"."helpful_cube_rating" to "authenticated";

grant update on table "public"."helpful_cube_rating" to "authenticated";

grant delete on table "public"."helpful_cube_rating" to "service_role";

grant insert on table "public"."helpful_cube_rating" to "service_role";

grant references on table "public"."helpful_cube_rating" to "service_role";

grant select on table "public"."helpful_cube_rating" to "service_role";

grant trigger on table "public"."helpful_cube_rating" to "service_role";

grant truncate on table "public"."helpful_cube_rating" to "service_role";

grant update on table "public"."helpful_cube_rating" to "service_role";


  create policy "Enable delete for users based on username"
  on "public"."helpful_cube_rating"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));



  create policy "Enable insert for authenticated users only"
  on "public"."helpful_cube_rating"
  as permissive
  for insert
  to authenticated
with check ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "Enable read access for all users"
  on "public"."helpful_cube_rating"
  as permissive
  for select
  to public
using (true);



