create extension if not exists "unaccent" with schema "extensions";

create type "public"."cube_version_types" as enum ('Base', 'Variant', 'Limited');

create type "public"."date_precision" as enum ('day', 'month', 'year');

create type "public"."submission_operation" as enum ('create', 'update');

create type "public"."submission_type" as enum ('cube', 'vendor');

drop trigger if exists "log_cube_models" on "public"."cube_models";

drop trigger if exists "notify_discord_new_cube" on "public"."cube_models";

drop trigger if exists "trg_price_alert_discord" on "public"."cube_vendor_links_snapshot";

drop trigger if exists "notify_discord_new_user" on "public"."profiles";

drop trigger if exists "notify_discord_new_user_report" on "public"."reports";

drop policy "Enable insert for Database Managers and Admins" on "public"."brands";

drop policy "Enable delete for Admins and Community Managers" on "public"."cube_models";

drop policy "Only Database Manager's and Admin's can insert" on "public"."cube_models";

drop policy "Only Database Manager's and Admin's can update" on "public"."cube_models";

drop policy "Enable insert for Admins and Database Managers only" on "public"."cube_types";

drop policy "Enable update for users based on email" on "public"."cube_types";

drop policy "Only Admins and Database Managers can insert" on "public"."cube_vendor_links";

drop policy "Enable delete for Database Managers and Admins" on "public"."cubes_model_features";

drop policy "Enable insert for Database Managers and Admins" on "public"."cubes_model_features";

drop policy "Enable read access for all users" on "public"."cubes_model_features";

drop policy "Enable insert for authenticated users only" on "public"."user_cubes";

drop policy "Enable read access for all users" on "public"."vendors";

drop policy "Only Admins and Database Managers can insert" on "public"."vendors";

drop policy "Only Database Managers and Admins can update" on "public"."vendors";

revoke delete on table "public"."cubes_model_features" from "anon";

revoke insert on table "public"."cubes_model_features" from "anon";

revoke references on table "public"."cubes_model_features" from "anon";

revoke select on table "public"."cubes_model_features" from "anon";

revoke trigger on table "public"."cubes_model_features" from "anon";

revoke truncate on table "public"."cubes_model_features" from "anon";

revoke update on table "public"."cubes_model_features" from "anon";

revoke delete on table "public"."cubes_model_features" from "authenticated";

revoke insert on table "public"."cubes_model_features" from "authenticated";

revoke references on table "public"."cubes_model_features" from "authenticated";

revoke select on table "public"."cubes_model_features" from "authenticated";

revoke trigger on table "public"."cubes_model_features" from "authenticated";

revoke truncate on table "public"."cubes_model_features" from "authenticated";

revoke update on table "public"."cubes_model_features" from "authenticated";

revoke delete on table "public"."cubes_model_features" from "service_role";

revoke insert on table "public"."cubes_model_features" from "service_role";

revoke references on table "public"."cubes_model_features" from "service_role";

revoke select on table "public"."cubes_model_features" from "service_role";

revoke trigger on table "public"."cubes_model_features" from "service_role";

revoke truncate on table "public"."cubes_model_features" from "service_role";

revoke update on table "public"."cubes_model_features" from "service_role";

alter table "public"."cube_models" drop constraint "cube_models_related_to_fkey";

alter table "public"."cube_models" drop constraint "cube_models_submitted_by_id_fkey";

alter table "public"."cube_models" drop constraint "cube_models_verified_by_id_fkey";

alter table "public"."cubes_model_features" drop constraint "cubes_model_features_cube_fkey";

alter table "public"."cubes_model_features" drop constraint "cubes_model_features_feature_fkey";

alter table "public"."vendors" drop constraint "vendors_country_iso_check";

drop view if exists "public"."v_achievement_rarity";

drop view if exists "public"."v_awards_category_winners";

drop view if exists "public"."v_detailed_cube_models";

drop view if exists "public"."v_detailed_profiles";

drop view if exists "public"."v_detailed_vendors";

drop view if exists "public"."v_user_stats";

alter table "public"."cube_models" drop constraint "cubes_pkey";

alter table "public"."cubes_model_features" drop constraint "cubes_model_features_pkey";

drop index if exists "public"."cubes_pkey";

drop index if exists "public"."cubes_model_features_pkey";

drop table "public"."cubes_model_features";


  create table "public"."cube_model_features" (
    "id" bigint generated by default as identity not null,
    "cube" text not null default ''::text,
    "feature" text not null default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "added_by_id" uuid
      );


alter table "public"."cube_model_features" enable row level security;


  create table "public"."cube_series" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "added_by_id" uuid
      );


alter table "public"."cube_series" enable row level security;


  create table "public"."cube_submission_features" (
    "id" bigint generated by default as identity not null,
    "cube_submission_id" bigint not null,
    "feature_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."cube_submission_features" enable row level security;


  create table "public"."cube_submissions" (
    "id" bigint generated by default as identity not null,
    "submission_id" bigint not null,
    "target_cube_id" bigint,
    "name" text not null,
    "version_type" public.cube_version_types not null,
    "image_url" text not null,
    "brand_id" bigint,
    "proposed_brand_name" text,
    "type_id" bigint,
    "proposed_type_name" text,
    "series_id" bigint,
    "proposed_series_name" text,
    "related_to_id" bigint,
    "release_date" date,
    "release_date_precision" public.date_precision,
    "weight" numeric,
    "size" text,
    "surface_finish" public.cube_surface_finishes,
    "discontinued" boolean not null,
    "created_at" timestamp with time zone not null default now(),
    "sub_type" public.cubes_subtypes not null,
    "affected_cube_model_id" bigint
      );


alter table "public"."cube_submissions" enable row level security;


  create table "public"."cube_vendor_link_submissions" (
    "id" bigint generated by default as identity not null,
    "cube_submission_id" bigint not null,
    "vendor_id" bigint not null,
    "url" text not null,
    "price" numeric not null,
    "available" boolean not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."cube_vendor_link_submissions" enable row level security;


  create table "public"."submissions" (
    "id" bigint generated by default as identity not null,
    "type" public.submission_type not null,
    "status" public.submission_status not null default 'Pending'::public.submission_status,
    "submitter_note" text,
    "reviewer_note" text,
    "reviewed_by_id" uuid,
    "submitted_by_id" uuid not null default auth.uid(),
    "reviewed_at" timestamp with time zone,
    "submitted_at" timestamp with time zone not null default now(),
    "operation" public.submission_operation not null
      );


alter table "public"."submissions" enable row level security;

alter table "public"."cube_models" alter column sub_type type "public"."cubes_subtypes" using sub_type::text::"public"."cubes_subtypes";

alter table "public"."brands" alter column "added_by_id" drop default;

alter table "public"."brands" alter column "added_by_id" drop not null;

alter table "public"."cube_models" drop column "model";

alter table "public"."cube_models" drop column "notes";

alter table "public"."cube_models" drop column "rating";

alter table "public"."cube_models" drop column "related_to";

alter table "public"."cube_models" drop column "series";

alter table "public"."cube_models" drop column "status";

alter table "public"."cube_models" drop column "submitted_by_id";

alter table "public"."cube_models" drop column "verified_at";

alter table "public"."cube_models" drop column "verified_by_id";

alter table "public"."cube_models" drop column "version_name";

alter table "public"."cube_models" add column "brand_id" bigint not null;

alter table "public"."cube_models" add column "name" text not null;

alter table "public"."cube_models" add column "related_to_id" bigint;

alter table "public"."cube_models" add column "release_date_precision" public.date_precision default 'year'::public.date_precision;

alter table "public"."cube_models" add column "series_id" bigint;

alter table "public"."cube_models" add column "type_id" bigint;

alter table "public"."cube_models" alter column "brand" drop default;

alter table "public"."cube_models" alter column "sub_type" set not null;

alter table "public"."cube_models" alter column "version_type" set default 'Base'::public.cube_version_types;

alter table "public"."cube_models" alter column "version_type" set data type public.cube_version_types using "version_type"::text::public.cube_version_types;

alter table "public"."cube_models" alter column "weight" drop not null;

alter table "public"."cube_models" alter column "weight" set data type numeric(7,2) using "weight"::numeric(7,2);

alter table "public"."cube_types" drop column "popularity";

alter table "public"."cube_types" drop column "shape_family";

alter table "public"."cube_types" add column "created_from_cube_id" bigint;

alter table "public"."cube_types" add column "status" public.submission_status not null default 'Pending'::public.submission_status;

alter table "public"."cube_vendor_links" add column "added_by_id" uuid;

alter table "public"."cube_vendor_links" add column "is_dead" boolean not null default false;

alter table "public"."cube_vendor_links" add column "vendor_id" bigint;

alter table "public"."cube_vendor_links" alter column "price" set data type numeric(12,2) using "price"::numeric(12,2);

alter table "public"."profiles" drop column "certified";

alter table "public"."vendors" drop column "is_active";

alter table "public"."vendors" drop column "rating";

alter table "public"."vendors" drop column "verified";

alter table "public"."vendors" add column "staff_note" text;

alter table "public"."vendors" add column "status" public.submission_status not null default 'Pending'::public.submission_status;

alter table "public"."vendors" add column "submitted_by_id" uuid;

alter table "public"."vendors" add column "supports_price_scraping" boolean not null default false;

alter table "public"."vendors" add column "supports_product_scraping" boolean not null default false;

alter table "public"."vendors" add column "verified_at" timestamp with time zone;

alter table "public"."vendors" add column "verified_by_id" uuid;

alter table "public"."vendors" alter column "currency" set default 'USD'::text;

alter table "public"."vendors" alter column "currency" set data type text using "currency"::text;

drop type "public"."cube_surface_finish";

drop type "public"."cube_version_type";

drop type "public"."currencies";

CREATE UNIQUE INDEX cube_models_name_key ON public.cube_models USING btree (name);

CREATE UNIQUE INDEX cube_models_pkey ON public.cube_models USING btree (id);

CREATE UNIQUE INDEX cube_series_name_key ON public.cube_series USING btree (name);

CREATE UNIQUE INDEX cube_series_pkey ON public.cube_series USING btree (id);

CREATE UNIQUE INDEX cube_submission_features_pkey ON public.cube_submission_features USING btree (id, cube_submission_id);

CREATE UNIQUE INDEX cube_submissions_pkey ON public.cube_submissions USING btree (id);

CREATE UNIQUE INDEX cube_vendor_link_submissions_pkey ON public.cube_vendor_link_submissions USING btree (id);

CREATE UNIQUE INDEX submissions_pkey ON public.submissions USING btree (id);

CREATE UNIQUE INDEX cubes_model_features_pkey ON public.cube_model_features USING btree (id, cube, feature);

alter table "public"."cube_model_features" add constraint "cubes_model_features_pkey" PRIMARY KEY using index "cubes_model_features_pkey";

alter table "public"."cube_models" add constraint "cube_models_pkey" PRIMARY KEY using index "cube_models_pkey";

alter table "public"."cube_series" add constraint "cube_series_pkey" PRIMARY KEY using index "cube_series_pkey";

alter table "public"."cube_submission_features" add constraint "cube_submission_features_pkey" PRIMARY KEY using index "cube_submission_features_pkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_pkey" PRIMARY KEY using index "cube_submissions_pkey";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_pkey" PRIMARY KEY using index "cube_vendor_link_submissions_pkey";

alter table "public"."submissions" add constraint "submissions_pkey" PRIMARY KEY using index "submissions_pkey";

alter table "public"."cube_model_features" add constraint "cube_model_features_added_by_id_fkey" FOREIGN KEY (added_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_model_features" validate constraint "cube_model_features_added_by_id_fkey";

alter table "public"."cube_model_features" add constraint "cubes_model_features_cube_fkey" FOREIGN KEY (cube) REFERENCES public.cube_models(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_model_features" validate constraint "cubes_model_features_cube_fkey";

alter table "public"."cube_model_features" add constraint "cubes_model_features_feature_fkey" FOREIGN KEY (feature) REFERENCES public.cube_features(code) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_model_features" validate constraint "cubes_model_features_feature_fkey";

alter table "public"."cube_models" add constraint "cube_models_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_models" validate constraint "cube_models_brand_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_name_key" UNIQUE using index "cube_models_name_key";

alter table "public"."cube_models" add constraint "cube_models_related_to_id_fkey" FOREIGN KEY (related_to_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_models" validate constraint "cube_models_related_to_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_release_date_complete_check" CHECK (((release_date IS NULL) = (release_date_precision IS NULL))) not valid;

alter table "public"."cube_models" validate constraint "cube_models_release_date_complete_check";

alter table "public"."cube_models" add constraint "cube_models_series_id_fkey" FOREIGN KEY (series_id) REFERENCES public.cube_series(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."cube_models" validate constraint "cube_models_series_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_type_id_fkey" FOREIGN KEY (type_id) REFERENCES public.cube_types(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_models" validate constraint "cube_models_type_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_weight_check" CHECK ((weight > (0)::numeric)) not valid;

alter table "public"."cube_models" validate constraint "cube_models_weight_check";

alter table "public"."cube_series" add constraint "cube_series_added_by_id_fkey" FOREIGN KEY (added_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_series" validate constraint "cube_series_added_by_id_fkey";

alter table "public"."cube_series" add constraint "cube_series_name_key" UNIQUE using index "cube_series_name_key";

alter table "public"."cube_submission_features" add constraint "cube_submission_features_cube_submission_id_fkey" FOREIGN KEY (cube_submission_id) REFERENCES public.cube_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submission_features" validate constraint "cube_submission_features_cube_submission_id_fkey";

alter table "public"."cube_submission_features" add constraint "cube_submission_features_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES public.cube_features(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submission_features" validate constraint "cube_submission_features_feature_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_affected_cube_model_id_fkey" FOREIGN KEY (affected_cube_model_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_affected_cube_model_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_brand_check" CHECK (((brand_id IS NOT NULL) <> (proposed_brand_name IS NOT NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_brand_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_brand_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_related_to_id_fkey" FOREIGN KEY (related_to_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_related_to_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_release_date_complete_check" CHECK (((release_date IS NULL) = (release_date_precision IS NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_release_date_complete_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_series_check" CHECK (((series_id IS NULL) OR (proposed_series_name IS NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_series_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_series_id_fkey" FOREIGN KEY (series_id) REFERENCES public.cube_series(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_series_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_size_check" CHECK ((size ~ '^[0-9]+(\.[0-9]+)?\sx\s[0-9]+(\.[0-9]+)?\sx\s[0-9]+(\.[0-9]+)?$'::text)) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_size_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_submission_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_target_cube_id_fkey" FOREIGN KEY (target_cube_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_target_cube_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_type_check" CHECK (((type_id IS NOT NULL) <> (proposed_type_name IS NOT NULL))) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_type_check";

alter table "public"."cube_submissions" add constraint "cube_submissions_type_id_fkey" FOREIGN KEY (type_id) REFERENCES public.cube_types(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_type_id_fkey";

alter table "public"."cube_submissions" add constraint "cube_submissions_weight_check" CHECK ((weight > (0)::numeric)) not valid;

alter table "public"."cube_submissions" validate constraint "cube_submissions_weight_check";

alter table "public"."cube_types" add constraint "cube_types_created_from_cube_id_fkey" FOREIGN KEY (created_from_cube_id) REFERENCES public.cube_models(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_types" validate constraint "cube_types_created_from_cube_id_fkey";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_cube_submission_id_fkey" FOREIGN KEY (cube_submission_id) REFERENCES public.cube_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_vendor_link_submissions" validate constraint "cube_vendor_link_submissions_cube_submission_id_fkey";

alter table "public"."cube_vendor_link_submissions" add constraint "cube_vendor_link_submissions_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_vendor_link_submissions" validate constraint "cube_vendor_link_submissions_vendor_id_fkey";

alter table "public"."cube_vendor_links" add constraint "cube_vendor_links_added_by_id_fkey" FOREIGN KEY (added_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_vendor_links" validate constraint "cube_vendor_links_added_by_id_fkey";

alter table "public"."cube_vendor_links" add constraint "cube_vendor_links_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cube_vendor_links" validate constraint "cube_vendor_links_vendor_id_fkey";

alter table "public"."submissions" add constraint "submissions_reviewed_by_id_fkey" FOREIGN KEY (reviewed_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."submissions" validate constraint "submissions_reviewed_by_id_fkey";

alter table "public"."submissions" add constraint "submissions_submitted_by_id_fkey" FOREIGN KEY (submitted_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."submissions" validate constraint "submissions_submitted_by_id_fkey";

alter table "public"."vendors" add constraint "vendors_currency_check" CHECK ((currency ~ '^[A-Z]{3}$'::text)) not valid;

alter table "public"."vendors" validate constraint "vendors_currency_check";

alter table "public"."vendors" add constraint "vendors_submitted_by_id_fkey" FOREIGN KEY (submitted_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."vendors" validate constraint "vendors_submitted_by_id_fkey";

alter table "public"."vendors" add constraint "vendors_verified_by_id_fkey" FOREIGN KEY (verified_by_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."vendors" validate constraint "vendors_verified_by_id_fkey";

alter table "public"."vendors" add constraint "vendors_country_iso_check" CHECK ((country_iso ~ '^[A-Z]{2}$'::text)) not valid;

alter table "public"."vendors" validate constraint "vendors_country_iso_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.approve_submission(p_submission_id bigint)
 RETURNS public.submissions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_reviewer_id uuid := auth.uid();
v_submission public.submissions;
begin if v_reviewer_id is null then raise exception using errcode = '42501',
message = 'Authentication required';
end if;
if not exists(
    select 1
    from public.profiles p
    where p.user_id = v_reviewer_id
        and p.role = any(
            array ['Admin'::public.users_roles, 'Database Manager'::public.users_roles]
        )
) then raise exception using errcode = '42501',
message = 'Only admins and detabase managers members can approve submissions';
end if;
select submission.* into v_submission
from public.submissions as submission
where submission.id = p_submission_id for
update;
if not found then raise exception using errcode = 'P0002',
message = format('Submission %s was not found', p_submission_id);
end if;
if v_submission.status <> 'Pending'::public.submission_status then raise exception using errcode = '55000',
message = format(
    'Submission %s cannot be approved because its status is %s',
    p_submission_id,
    v_submission.status
);
end if;
update public.submissions
set status = 'Approved'::public.submission_status,
    reviewed_by_id = v_reviewer_id,
    reviewed_at = now()
where id = p_submission_id
returning * into v_submission;
return v_submission;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_submission(p_submission_id bigint, p_reviewer_note text)
 RETURNS public.submissions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_reviewer_id uuid := auth.uid();
v_submission public.submissions;
begin if v_reviewer_id is null then raise exception using errcode = '42501',
message = 'Authentication required';
end if;
if not exists(
    select 1
    from public.profiles p
    where p.user_id = v_reviewer_id
        and p.role = any(
            array ['Admin'::public.users_roles, 'Database Manager'::public.users_roles]
        )
) then raise exception using errcode = '42501',
message = 'Only admins and database managers members can reject submissions';
end if;
if nullif(btrim(p_reviewer_note), '') is null then raise exception using errcode = '22023',
message = 'A reviewer note is required when rejecting a submission';
end if;
select submission.* into v_submission
from public.submissions as submission
where submission.id = p_submission_id for
update;
if not found then raise exception using errcode = 'P0002',
message = format('Submission %s was not found', p_submission_id);
end if;
if v_submission.status <> 'Pending'::public.submission_status then raise exception using errcode = '55000',
message = format(
    'Submission %s cannot be rejected because its status is %s',
    p_submission_id,
    v_submission.status
);
end if;
update public.submissions
set status = 'Rejected'::public.submission_status,
    reviewer_note = btrim(p_reviewer_note),
    reviewed_by_id = v_reviewer_id,
    reviewed_at = now()
where id = p_submission_id
returning * into v_submission;
return v_submission;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_cube(p_operation public.submission_operation, p_submitter_note text DEFAULT NULL::text, p_cube jsonb DEFAULT '{}'::jsonb, p_feature_ids bigint[] DEFAULT '{}'::bigint[], p_vendor_links jsonb DEFAULT '[]'::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare v_user_id uuid := auth.uid();
v_submission_id bigint;
v_cube_submission_id bigint;
v_cube record;
v_vendor_link jsonb;
begin if v_user_id is null then raise exception 'Authentication required' using errcode = '42501';
end if;
select * into v_cube
from jsonb_to_record(p_cube) as cube_data (
        target_cube_id bigint,
        name text,
        version_type public.cube_version_types,
        image_url text,
        brand_id bigint,
        proposed_brand_name text,
        type_id bigint,
        proposed_type_name text,
        series_id bigint,
        proposed_series_name text,
        related_to_id bigint,
        release_date date,
        release_date_precision public.date_precision,
        sub_type public.cubes_subtypes,
        weight numeric,
        size text,
        surface_finish public.cube_surface_finishes,
        discontinued boolean
    );
if p_operation = 'create'::public.submission_operation
and v_cube.target_cube_id is not null then raise exception 'Create submissions cannot target an existing cube' using errcode = '22023';
elsif p_operation = 'update'::public.submission_operation
and v_cube.target_cube_id is null then raise exception 'Update submissions require target_cube_id' using errcode = '22023';
end if;
insert into public.submissions (
        type,
        status,
        submitter_note,
        submitted_by_id,
        operation
    )
values (
        'cube'::public.submission_type,
        'Pending'::public.submission_status,
        p_submitter_note,
        v_user_id,
        p_operation
    )
returning id into v_submission_id;
insert into public.cube_submissions (
        submission_id,
        target_cube_id,
        name,
        version_type,
        image_url,
        brand_id,
        proposed_brand_name,
        type_id,
        proposed_type_name,
        series_id,
        proposed_series_name,
        related_to_id,
        release_date,
        release_date_precision,
        sub_type,
        weight,
        size,
        surface_finish,
        discontinued
    )
values (
        v_submission_id,
        v_cube.target_cube_id,
        v_cube.name,
        v_cube.version_type,
        v_cube.image_url,
        v_cube.brand_id,
        v_cube.proposed_brand_name,
        v_cube.type_id,
        v_cube.proposed_type_name,
        v_cube.series_id,
        v_cube.proposed_series_name,
        v_cube.related_to_id,
        v_cube.release_date,
        v_cube.release_date_precision,
        v_cube.sub_type,
        v_cube.weight,
        v_cube.size,
        v_cube.surface_finish,
        v_cube.discontinued
    )
returning id into v_cube_submission_id;
insert into public.cube_submission_features (cube_submission_id, feature_id)
select v_cube_submission_id,
    proposed.feature_id
from (
        select distinct feature_id
        from unnest(p_feature_ids) as values_list(feature_id)
        where feature_id is not null
    ) proposed;
for v_vendor_link in
select value
from jsonb_array_elements(p_vendor_links) loop if p_operation = 'create'::submission_operation
    and v_vendor_link->>'target_cube_vendor_link_id' is not null then raise exception 'A create submission cannot have a target cube vendor link' using errcode = '22023';
elsif p_operation = 'update'::submission_operation
and v_vendor_link->>'target_cube_vendor_link_id' is null then raise exception 'An update submission requires a target cube vendor link' using errcode = '22023';
end if;
insert into public.cube_vendor_link_submissions (
        cube_submission_id,
        vendor_id,
        url,
        price,
        available
    )
values (
        v_cube_submission_id,
        (v_vendor_link->>'vendor_id')::bigint,
        (v_vendor_link->>'url')::text,
        (v_vendor_link->>'price')::numeric,
        (v_vendor_link->>'available')::boolean
    );
end loop;
return v_submission_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.build_v_detailed_cube_models()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  cols text := '';
  r record;
  colname text;
begin
  -- Build ", exists(...) as <col>" for each feature
  for r in
    select code
    from cube_features
    order by code
  loop
    -- Make a safe SQL identifier from the feature code
    colname := r.code;

    cols := cols || format(
      ', exists (select 1
                 from cubes_model_features f
                 where f.cube = cm.slug
                   and f.feature = %L) as %I',
      r.code,      -- literal (e.g., 'wca_legal')
      colname      -- identifier (e.g., wca_legal)
    );
  end loop;

  -- Create the view
  execute format($sql$
    create or replace view public.v_detailed_cube_models as
    select
      cm.* %s,
      extract(year from cm.release_date)::int as year,
      (select count(*) from user_cubes uc where uc.cube = cm.slug) as popularity,
      (select avg(price) from cube_vendor_links cvl where cvl.cube_slug = cm.slug and (select currency from vendors v where cvl.vendor_name = v.name) = 'USD') as avg_price
    from cube_models cm
  $sql$, cols);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.log_data_changes()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$declare
  actor uuid;
begin
  actor := coalesce(auth.uid(), '898d0e3a-3465-4c25-9b9f-b498b9884d1d'::uuid);

  if TG_OP = 'INSERT' then
    insert into public.staff_logs (staff_id, action, target_table, old_data, new_data)
    values (
      actor,
      TG_OP::public.staff_actions,
      TG_TABLE_NAME,
      null,
      to_jsonb(NEW)
    );

    return NEW;

  elsif TG_OP = 'UPDATE' then
    if to_jsonb(OLD) <> to_jsonb(NEW) then
      insert into public.staff_logs (staff_id, action, target_table, old_data, new_data)
      values (
        actor,
        TG_OP::public.staff_actions,
        TG_TABLE_NAME,
        to_jsonb(OLD),
        to_jsonb(NEW)
      );
    end if;

    return NEW;

  elsif TG_OP = 'DELETE' then
    insert into public.staff_logs (staff_id, action, target_table, old_data, new_data)
    values (
      actor,
      TG_OP::public.staff_actions,
      TG_TABLE_NAME,
      to_jsonb(OLD),
      null
    );

    return OLD;

  else
    return null;
  end if;
end;$function$
;

create or replace view "public"."v_achievement_rarity" as  WITH eligible AS (
         SELECT (count(*))::numeric AS n
           FROM public.profiles
          WHERE (COALESCE(profiles.onboarded, false) = true)
        ), counts AS (
         SELECT a.id,
            a.name,
            a.icon,
            a.description,
            a.created_at,
            a.updated_at,
            a.unlockable,
            a.slug,
            a.unlock_method,
            a.rarity,
            a.category,
            a.title,
            a.evolutive,
            a.evolves_from,
            a.submitted_by_id,
            a.is_special,
            a.hidden,
            (COALESCE(count(ua.user_id), (0)::bigint))::integer AS holders_count
           FROM (public.achievements a
             LEFT JOIN public.user_achievements ua ON ((ua.achievement_slug = a.slug)))
          GROUP BY a.id, a.slug, a.name, a.icon, a.description, a.category, a.title, a.unlock_method, a.unlockable, a.hidden, a.is_special, a.created_at
        ), scored AS (
         SELECT c.id,
            c.slug,
            c.name,
            c.icon,
            c.description,
            c.category,
            c.title,
            c.unlock_method,
            c.unlockable,
            c.hidden,
            c.is_special,
            c.holders_count,
            c.created_at,
                CASE
                    WHEN (e.n = (0)::numeric) THEN (0)::numeric
                    ELSE round((((100)::numeric * (c.holders_count)::numeric) / e.n), 2)
                END AS rarity_percent
           FROM (counts c
             CROSS JOIN eligible e)
        )
 SELECT scored.id,
    scored.slug,
    scored.name,
    scored.icon,
    scored.description,
    scored.category,
    scored.title,
    scored.unlock_method,
    scored.unlockable,
    scored.hidden,
    scored.holders_count,
    scored.rarity_percent,
    scored.created_at,
        CASE
            WHEN scored.is_special THEN 'Special'::text
            WHEN (scored.holders_count = 0) THEN 'Legendary'::text
            WHEN ((((100)::numeric * (scored.holders_count)::numeric) / NULLIF(( SELECT eligible.n
               FROM eligible), (0)::numeric)) < (1)::numeric) THEN 'Legendary'::text
            WHEN ((((100)::numeric * (scored.holders_count)::numeric) / NULLIF(( SELECT eligible.n
               FROM eligible), (0)::numeric)) < (5)::numeric) THEN 'Epic'::text
            WHEN ((((100)::numeric * (scored.holders_count)::numeric) / NULLIF(( SELECT eligible.n
               FROM eligible), (0)::numeric)) < (20)::numeric) THEN 'Rare'::text
            WHEN ((((100)::numeric * (scored.holders_count)::numeric) / NULLIF(( SELECT eligible.n
               FROM eligible), (0)::numeric)) < (50)::numeric) THEN 'Uncommon'::text
            ELSE 'Common'::text
        END AS rarity
   FROM scored;


create or replace view "public"."v_awards_category_winners" as  WITH votes AS (
         SELECT an.category_id,
            cm.slug AS nominee_slug,
            count(DISTINCT auv.user_id) AS vote_count
           FROM ((public.awards_nominee an
             JOIN public.cube_models cm ON ((cm.id = an.cube_id)))
             LEFT JOIN public.awards_user_vote auv ON ((auv.nominee_id = an.id)))
          GROUP BY an.category_id, cm.slug
        ), ranked AS (
         SELECT v.category_id,
            v.nominee_slug,
            v.vote_count,
            dense_rank() OVER (PARTITION BY v.category_id ORDER BY v.vote_count DESC) AS rnk
           FROM votes v
        )
 SELECT r.category_id,
    r.nominee_slug,
    r.vote_count,
    ( SELECT count(*) AS count
           FROM public.awards_nominee an
          WHERE (an.category_id = r.category_id)) AS nominee_count
   FROM ranked r
  WHERE (r.rnk = 1);


create or replace view "public"."v_detailed_cube_models" as  SELECT cm.brand_id,
    cm.image_url,
    cm.slug,
    cm.created_at,
    cm.updated_at,
    cm.type_id,
    cm.discontinued,
    cm.release_date,
    cm.id,
    cm.sub_type,
    cm.weight,
    cm.version_type,
    cm.surface_finish,
    cm.size,
    cm.series_id,
    cm.name,
    cm.related_to_id,
    cm.release_date_precision,
    v.name AS image_source,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'ball_core'::text)))) AS ball_core,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'maglev'::text)))) AS maglev,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'magnetic'::text)))) AS magnetic,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'modded'::text)))) AS modded,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'smart'::text)))) AS smart,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'stickered'::text)))) AS stickered,
    (EXISTS ( SELECT 1
           FROM public.cube_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'wca_legal'::text)))) AS wca_legal,
    (EXTRACT(year FROM cm.release_date))::integer AS year,
    ( SELECT cs.name
           FROM public.cube_series cs
          WHERE (cm.series_id = cs.id)) AS series,
    ( SELECT b.name
           FROM public.brands b
          WHERE (cm.brand_id = b.id)) AS brand,
    ( SELECT t.name
           FROM public.cube_types t
          WHERE (cm.type_id = t.id)) AS type,
    ( SELECT cube_models.name
           FROM public.cube_models
          WHERE (cm.related_to_id = cube_models.id)) AS related_to,
    ( SELECT count(*) AS count
           FROM public.user_cubes uc
          WHERE (uc.cube = cm.slug)) AS popularity,
    ( SELECT avg(cvl.price) AS avg
           FROM public.cube_vendor_links cvl
          WHERE ((cvl.cube_slug = cm.slug) AND (( SELECT v_1.currency
                   FROM public.vendors v_1
                  WHERE (cvl.vendor_name = v_1.name)) = 'USD'::text))) AS avg_price,
    ( SELECT min(cvl.price) AS min
           FROM public.cube_vendor_links cvl
          WHERE ((cvl.cube_slug = cm.slug) AND (( SELECT v_1.currency
                   FROM public.vendors v_1
                  WHERE (cvl.vendor_name = v_1.name)) = 'USD'::text))) AS low_price,
    ( SELECT avg(ucr.rating) AS avg
           FROM public.user_cube_ratings ucr
          WHERE (ucr.cube_slug = cm.slug)) AS rating,
    ( SELECT count(ucr.rating) AS count
           FROM public.user_cube_ratings ucr
          WHERE (ucr.cube_slug = cm.slug)) AS rating_count
   FROM (public.cube_models cm
     LEFT JOIN public.vendors v ON ((lower(regexp_replace(split_part(regexp_replace(cm.image_url, '^https?://'::text, ''::text), '/'::text, 1), '^www\.'::text, ''::text)) = lower(regexp_replace(split_part(regexp_replace(v.base_url, '^https?://'::text, ''::text), '/'::text, 1), '^www\.'::text, ''::text)))));


create or replace view "public"."v_detailed_profiles" as  SELECT p.id,
    p.created_at,
    p.user_id,
    p.username,
    p.private,
    p.profile_picture,
    p.bio,
    p.socials,
    p.banner,
    p.verified,
    p.role,
    p.display_name,
    p.onboarded,
    COALESCE(uc.cube_count, (0)::bigint) AS user_cubes_count,
    COALESCE(ua.achievement_count, (0)::bigint) AS user_achievements_count,
    COALESCE(fwing.following_count, (0)::bigint) AS user_following_count,
    COALESCE(fwer.follower_count, (0)::bigint) AS user_follower_count,
    COALESCE(ur.ratings_count, (0)::bigint) AS user_cube_ratings_count,
    COALESCE(ur.rating_avg, (0)::double precision) AS user_avg_rating_count,
    COALESCE((ucr.reviews_count)::double precision, (0)::double precision) AS cube_reviews_count
   FROM ((((((public.profiles p
     LEFT JOIN ( SELECT user_cubes.user_id,
            count(*) AS cube_count
           FROM public.user_cubes
          GROUP BY user_cubes.user_id) uc ON ((uc.user_id = p.user_id)))
     LEFT JOIN ( SELECT user_achievements.user_id,
            count(*) AS achievement_count
           FROM public.user_achievements
          GROUP BY user_achievements.user_id) ua ON ((ua.user_id = p.user_id)))
     LEFT JOIN ( SELECT user_follows.follower_id,
            count(*) AS following_count
           FROM public.user_follows
          GROUP BY user_follows.follower_id) fwing ON ((fwing.follower_id = p.user_id)))
     LEFT JOIN ( SELECT user_follows.following_id,
            count(*) AS follower_count
           FROM public.user_follows
          GROUP BY user_follows.following_id) fwer ON ((fwer.following_id = p.user_id)))
     LEFT JOIN ( SELECT user_cube_ratings.user_id,
            count(*) AS ratings_count,
            avg(user_cube_ratings.rating) AS rating_avg
           FROM public.user_cube_ratings
          GROUP BY user_cube_ratings.user_id) ur ON ((ur.user_id = p.user_id)))
     LEFT JOIN ( SELECT ucr_1.user_id,
            count(*) AS reviews_count
           FROM public.user_cube_reviews ucr_1
          WHERE (ucr_1.status = 'published'::public.cube_review_status)
          GROUP BY ucr_1.user_id) ucr ON ((ucr.user_id = p.user_id)));


create or replace view "public"."v_detailed_vendors" as  SELECT v.id,
    v.slug,
    v.created_at,
    v.name,
    v.base_url,
    v.country_iso,
    v.updated_at,
    v.logo_url,
    v.currency,
    v.sponsored,
    v.supports_product_scraping,
    v.supports_price_scraping,
    v.status,
    v.staff_note,
    v.submitted_by_id,
    v.verified_by_id,
    v.verified_at,
    ( SELECT count(DISTINCT uc.user_id) AS count
           FROM public.user_cubes uc
          WHERE (uc.bought_from = v.slug)) AS buyer_count
   FROM public.vendors v;


create or replace view "public"."v_user_stats" as  WITH cube_stats AS (
         SELECT uc.user_id,
            count(*) AS cube_count,
            sum(uc.purchase_price) AS collection_value
           FROM public.user_cubes uc
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY uc.user_id
        ), rating_stats AS (
         SELECT user_cube_ratings.user_id,
            avg(user_cube_ratings.rating) AS rating_avg,
            count(*) AS rating_count
           FROM public.user_cube_ratings
          GROUP BY user_cube_ratings.user_id
        ), brand_counts AS (
         SELECT uc.user_id,
            cm.brand,
            count(*) AS cnt
           FROM (public.user_cubes uc
             JOIN public.cube_models cm ON ((cm.slug = uc.cube)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY cm.brand, uc.user_id
        ), type_counts AS (
         SELECT uc.user_id,
            cm.type,
            count(*) AS cnt
           FROM (public.user_cubes uc
             JOIN public.cube_models cm ON ((cm.slug = uc.cube)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY cm.type, uc.user_id
        ), store_counts AS (
         SELECT uc.user_id,
            v.name AS store,
            count(*) AS cnt
           FROM (public.user_cubes uc
             JOIN public.vendors v ON ((v.slug = uc.bought_from)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY v.name, uc.user_id
        ), condition_counts AS (
         SELECT uc.user_id,
            uc.condition,
            count(*) AS cnt
           FROM public.user_cubes uc
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY uc.condition, uc.user_id
        ), cubes_over_time_counts AS (
         SELECT user_cubes.user_id,
            (date_trunc('month'::text, (user_cubes.acquired_at)::timestamp with time zone))::date AS month,
            count(*) AS cnt
           FROM public.user_cubes
          WHERE ((user_cubes.acquired_at IS NOT NULL) AND (user_cubes.status <> 'Wishlist'::public.user_cube_status))
          GROUP BY user_cubes.user_id, ((date_trunc('month'::text, (user_cubes.acquired_at)::timestamp with time zone))::date)
        ), brand_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.brand
                    ELSE 'Other'::text
                END AS brand,
            sum(t.cnt) AS cnt
           FROM ( SELECT brand_counts.user_id,
                    brand_counts.brand,
                    brand_counts.cnt,
                    row_number() OVER (PARTITION BY brand_counts.user_id ORDER BY brand_counts.cnt DESC) AS rn
                   FROM brand_counts
                  WHERE (brand_counts.brand IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.brand
                    ELSE 'Other'::text
                END
        ), store_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.store
                    ELSE 'Other'::text
                END AS store,
            sum(t.cnt) AS cnt
           FROM ( SELECT store_counts.user_id,
                    store_counts.store,
                    store_counts.cnt,
                    row_number() OVER (PARTITION BY store_counts.user_id ORDER BY store_counts.cnt DESC) AS rn
                   FROM store_counts
                  WHERE (store_counts.store IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.store
                    ELSE 'Other'::text
                END
        ), type_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.type
                    ELSE 'Other'::text
                END AS type,
            sum(t.cnt) AS cnt
           FROM ( SELECT type_counts.user_id,
                    type_counts.type,
                    type_counts.cnt,
                    row_number() OVER (PARTITION BY type_counts.user_id ORDER BY type_counts.cnt DESC) AS rn
                   FROM type_counts
                  WHERE (type_counts.type IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.type
                    ELSE 'Other'::text
                END
        ), condition_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN (t.condition)::text
                    ELSE 'Other'::text
                END AS condition,
            sum(t.cnt) AS cnt
           FROM ( SELECT condition_counts.user_id,
                    condition_counts.condition,
                    condition_counts.cnt,
                    row_number() OVER (PARTITION BY condition_counts.user_id ORDER BY condition_counts.cnt DESC) AS rn
                   FROM condition_counts
                  WHERE (condition_counts.condition IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN (t.condition)::text
                    ELSE 'Other'::text
                END
        ), cubes_per_brand AS (
         SELECT brand_grouped.user_id,
            COALESCE(jsonb_object_agg(brand_grouped.brand, brand_grouped.cnt) FILTER (WHERE (brand_grouped.brand IS NOT NULL)), '{}'::jsonb) AS cubes_per_brand
           FROM brand_grouped
          GROUP BY brand_grouped.user_id
        ), cubes_per_store AS (
         SELECT store_grouped.user_id,
            COALESCE(jsonb_object_agg(store_grouped.store, store_grouped.cnt) FILTER (WHERE (store_grouped.store IS NOT NULL)), '{}'::jsonb) AS cubes_per_store
           FROM store_grouped
          GROUP BY store_grouped.user_id
        ), cubes_per_type AS (
         SELECT type_grouped.user_id,
            COALESCE(jsonb_object_agg(type_grouped.type, type_grouped.cnt) FILTER (WHERE (type_grouped.type IS NOT NULL)), '{}'::jsonb) AS cubes_per_type
           FROM type_grouped
          GROUP BY type_grouped.user_id
        ), cubes_per_condition AS (
         SELECT condition_grouped.user_id,
            COALESCE(jsonb_object_agg(condition_grouped.condition, condition_grouped.cnt) FILTER (WHERE (condition_grouped.condition IS NOT NULL)), '{}'::jsonb) AS cubes_per_condition
           FROM condition_grouped
          GROUP BY condition_grouped.user_id
        ), cubes_over_time AS (
         SELECT cubes_over_time_counts.user_id,
            COALESCE(jsonb_object_agg(to_char((cubes_over_time_counts.month)::timestamp with time zone, 'YYYY-MM'::text), cubes_over_time_counts.cnt ORDER BY cubes_over_time_counts.month), '{}'::jsonb) AS cubes_over_time
           FROM cubes_over_time_counts
          GROUP BY cubes_over_time_counts.user_id
        )
 SELECT cs.user_id,
    cs.cube_count,
    cs.collection_value,
    rs.rating_count,
    rs.rating_avg,
    cb.cubes_per_brand,
    cps.cubes_per_store,
    cot.cubes_over_time,
    ct.cubes_per_type,
    cp.cubes_per_condition
   FROM ((((((cube_stats cs
     LEFT JOIN rating_stats rs ON ((rs.user_id = cs.user_id)))
     LEFT JOIN cubes_per_brand cb ON ((cb.user_id = cs.user_id)))
     LEFT JOIN cubes_per_store cps ON ((cps.user_id = cs.user_id)))
     LEFT JOIN cubes_over_time cot ON ((cot.user_id = cs.user_id)))
     LEFT JOIN cubes_per_type ct ON ((ct.user_id = cs.user_id)))
     LEFT JOIN cubes_per_condition cp ON ((cp.user_id = cs.user_id)));


grant delete on table "public"."cube_model_features" to "anon";

grant insert on table "public"."cube_model_features" to "anon";

grant references on table "public"."cube_model_features" to "anon";

grant select on table "public"."cube_model_features" to "anon";

grant trigger on table "public"."cube_model_features" to "anon";

grant truncate on table "public"."cube_model_features" to "anon";

grant update on table "public"."cube_model_features" to "anon";

grant delete on table "public"."cube_model_features" to "authenticated";

grant insert on table "public"."cube_model_features" to "authenticated";

grant references on table "public"."cube_model_features" to "authenticated";

grant select on table "public"."cube_model_features" to "authenticated";

grant trigger on table "public"."cube_model_features" to "authenticated";

grant truncate on table "public"."cube_model_features" to "authenticated";

grant update on table "public"."cube_model_features" to "authenticated";

grant delete on table "public"."cube_model_features" to "service_role";

grant insert on table "public"."cube_model_features" to "service_role";

grant references on table "public"."cube_model_features" to "service_role";

grant select on table "public"."cube_model_features" to "service_role";

grant trigger on table "public"."cube_model_features" to "service_role";

grant truncate on table "public"."cube_model_features" to "service_role";

grant update on table "public"."cube_model_features" to "service_role";

grant delete on table "public"."cube_series" to "anon";

grant insert on table "public"."cube_series" to "anon";

grant references on table "public"."cube_series" to "anon";

grant select on table "public"."cube_series" to "anon";

grant trigger on table "public"."cube_series" to "anon";

grant truncate on table "public"."cube_series" to "anon";

grant update on table "public"."cube_series" to "anon";

grant delete on table "public"."cube_series" to "authenticated";

grant insert on table "public"."cube_series" to "authenticated";

grant references on table "public"."cube_series" to "authenticated";

grant select on table "public"."cube_series" to "authenticated";

grant trigger on table "public"."cube_series" to "authenticated";

grant truncate on table "public"."cube_series" to "authenticated";

grant update on table "public"."cube_series" to "authenticated";

grant delete on table "public"."cube_series" to "service_role";

grant insert on table "public"."cube_series" to "service_role";

grant references on table "public"."cube_series" to "service_role";

grant select on table "public"."cube_series" to "service_role";

grant trigger on table "public"."cube_series" to "service_role";

grant truncate on table "public"."cube_series" to "service_role";

grant update on table "public"."cube_series" to "service_role";

grant delete on table "public"."cube_submission_features" to "anon";

grant insert on table "public"."cube_submission_features" to "anon";

grant references on table "public"."cube_submission_features" to "anon";

grant select on table "public"."cube_submission_features" to "anon";

grant trigger on table "public"."cube_submission_features" to "anon";

grant truncate on table "public"."cube_submission_features" to "anon";

grant update on table "public"."cube_submission_features" to "anon";

grant delete on table "public"."cube_submission_features" to "authenticated";

grant insert on table "public"."cube_submission_features" to "authenticated";

grant references on table "public"."cube_submission_features" to "authenticated";

grant select on table "public"."cube_submission_features" to "authenticated";

grant trigger on table "public"."cube_submission_features" to "authenticated";

grant truncate on table "public"."cube_submission_features" to "authenticated";

grant update on table "public"."cube_submission_features" to "authenticated";

grant delete on table "public"."cube_submission_features" to "service_role";

grant insert on table "public"."cube_submission_features" to "service_role";

grant references on table "public"."cube_submission_features" to "service_role";

grant select on table "public"."cube_submission_features" to "service_role";

grant trigger on table "public"."cube_submission_features" to "service_role";

grant truncate on table "public"."cube_submission_features" to "service_role";

grant update on table "public"."cube_submission_features" to "service_role";

grant delete on table "public"."cube_submissions" to "anon";

grant insert on table "public"."cube_submissions" to "anon";

grant references on table "public"."cube_submissions" to "anon";

grant select on table "public"."cube_submissions" to "anon";

grant trigger on table "public"."cube_submissions" to "anon";

grant truncate on table "public"."cube_submissions" to "anon";

grant update on table "public"."cube_submissions" to "anon";

grant delete on table "public"."cube_submissions" to "authenticated";

grant insert on table "public"."cube_submissions" to "authenticated";

grant references on table "public"."cube_submissions" to "authenticated";

grant select on table "public"."cube_submissions" to "authenticated";

grant trigger on table "public"."cube_submissions" to "authenticated";

grant truncate on table "public"."cube_submissions" to "authenticated";

grant update on table "public"."cube_submissions" to "authenticated";

grant delete on table "public"."cube_submissions" to "service_role";

grant insert on table "public"."cube_submissions" to "service_role";

grant references on table "public"."cube_submissions" to "service_role";

grant select on table "public"."cube_submissions" to "service_role";

grant trigger on table "public"."cube_submissions" to "service_role";

grant truncate on table "public"."cube_submissions" to "service_role";

grant update on table "public"."cube_submissions" to "service_role";

grant delete on table "public"."cube_vendor_link_submissions" to "anon";

grant insert on table "public"."cube_vendor_link_submissions" to "anon";

grant references on table "public"."cube_vendor_link_submissions" to "anon";

grant select on table "public"."cube_vendor_link_submissions" to "anon";

grant trigger on table "public"."cube_vendor_link_submissions" to "anon";

grant truncate on table "public"."cube_vendor_link_submissions" to "anon";

grant update on table "public"."cube_vendor_link_submissions" to "anon";

grant delete on table "public"."cube_vendor_link_submissions" to "authenticated";

grant insert on table "public"."cube_vendor_link_submissions" to "authenticated";

grant references on table "public"."cube_vendor_link_submissions" to "authenticated";

grant select on table "public"."cube_vendor_link_submissions" to "authenticated";

grant trigger on table "public"."cube_vendor_link_submissions" to "authenticated";

grant truncate on table "public"."cube_vendor_link_submissions" to "authenticated";

grant update on table "public"."cube_vendor_link_submissions" to "authenticated";

grant delete on table "public"."cube_vendor_link_submissions" to "service_role";

grant insert on table "public"."cube_vendor_link_submissions" to "service_role";

grant references on table "public"."cube_vendor_link_submissions" to "service_role";

grant select on table "public"."cube_vendor_link_submissions" to "service_role";

grant trigger on table "public"."cube_vendor_link_submissions" to "service_role";

grant truncate on table "public"."cube_vendor_link_submissions" to "service_role";

grant update on table "public"."cube_vendor_link_submissions" to "service_role";

grant delete on table "public"."submissions" to "anon";

grant insert on table "public"."submissions" to "anon";

grant references on table "public"."submissions" to "anon";

grant select on table "public"."submissions" to "anon";

grant trigger on table "public"."submissions" to "anon";

grant truncate on table "public"."submissions" to "anon";

grant update on table "public"."submissions" to "anon";

grant delete on table "public"."submissions" to "authenticated";

grant insert on table "public"."submissions" to "authenticated";

grant references on table "public"."submissions" to "authenticated";

grant select on table "public"."submissions" to "authenticated";

grant trigger on table "public"."submissions" to "authenticated";

grant truncate on table "public"."submissions" to "authenticated";

grant update on table "public"."submissions" to "authenticated";

grant delete on table "public"."submissions" to "service_role";

grant insert on table "public"."submissions" to "service_role";

grant references on table "public"."submissions" to "service_role";

grant select on table "public"."submissions" to "service_role";

grant trigger on table "public"."submissions" to "service_role";

grant truncate on table "public"."submissions" to "service_role";

grant update on table "public"."submissions" to "service_role";


  create policy "Only verified users can insert"
  on "public"."brands"
  as permissive
  for insert
  to authenticated
with check (((added_by_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.verified = true) AND (profiles.onboarded = true))))));



  create policy "Enable delete for Database Managers and Admins"
  on "public"."cube_model_features"
  as permissive
  for delete
  to authenticated
using ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.user_id = auth.uid())) = ANY (ARRAY['Database Manager'::public.users_roles, 'Admin'::public.users_roles])));



  create policy "Enable insert for verified profiles"
  on "public"."cube_model_features"
  as permissive
  for insert
  to authenticated
with check (((added_by_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.onboarded = true) AND (profiles.verified = true))))));



  create policy "Enable read access for all users"
  on "public"."cube_model_features"
  as permissive
  for select
  to public
using (true);



  create policy "Only Database Managers and Admins can update"
  on "public"."cube_models"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = ( SELECT auth.uid() AS uid)) AND (profiles.role = ANY (ARRAY['Database Manager'::public.users_roles, 'Admin'::public.users_roles]))))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = ( SELECT auth.uid() AS uid)) AND (profiles.role = ANY (ARRAY['Database Manager'::public.users_roles, 'Admin'::public.users_roles]))))));



  create policy "Enable read access for all users"
  on "public"."cube_series"
  as permissive
  for select
  to public
using (true);



  create policy "Only verified users can insert"
  on "public"."cube_series"
  as permissive
  for insert
  to authenticated
with check (((added_by_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.verified = true) AND (profiles.onboarded = true))))));



  create policy "Users can only see their submissions"
  on "public"."cube_submission_features"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.cube_submissions cs
     JOIN public.submissions s ON ((s.id = cs.submission_id)))
  WHERE ((cs.id = cube_submission_features.cube_submission_id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Admin and Database Managers can see all rows"
  on "public"."cube_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.user_id = ( SELECT auth.uid() AS uid)) AND (p.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Users can see their own submissions"
  on "public"."cube_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.submissions s
  WHERE ((cube_submissions.submission_id = s.id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Only verified users can insert"
  on "public"."cube_types"
  as permissive
  for insert
  to authenticated
with check (((added_by_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.verified = true) AND (profiles.onboarded = true))))));



  create policy "Users can only see their submissions"
  on "public"."cube_vendor_link_submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.cube_submissions cs
     JOIN public.submissions s ON ((s.id = cs.submission_id)))
  WHERE ((cube_vendor_link_submissions.cube_submission_id = cs.id) AND (s.submitted_by_id = ( SELECT auth.uid() AS uid))))));



  create policy "Only authenticated users can insert"
  on "public"."cube_vendor_links"
  as permissive
  for insert
  to public
with check ((added_by_id = auth.uid()));



  create policy "Admins and Database Managers can select submissions"
  on "public"."submissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Users can only see their own submissions"
  on "public"."submissions"
  as permissive
  for select
  to authenticated
using ((submitted_by_id = auth.uid()));



  create policy "Enable insert for verified users only"
  on "public"."user_cubes"
  as permissive
  for insert
  to authenticated
with check (((user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.verified = true) AND (profiles.onboarded = true))))));



  create policy "Authenticated users can submit vendors"
  on "public"."vendors"
  as permissive
  for all
  to authenticated
with check (((submitted_by_id = auth.uid()) AND (status = 'Pending'::public.submission_status) AND (staff_note IS NULL) AND (verified_by_id IS NULL) AND (verified_at IS NULL) AND (NOT supports_price_scraping) AND (NOT supports_product_scraping) AND ((logo_url IS NULL) OR (logo_url ~~ (('%/storage/v1/object/public/vendors-images/'::text || (auth.uid())::text) || '/%'::text)))));



  create policy "Database managers can insert vendors"
  on "public"."vendors"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Database managers can update vendors"
  on "public"."vendors"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles]))))));



  create policy "Read approved or own vendor submissions"
  on "public"."vendors"
  as permissive
  for select
  to public
using (((status = 'Approved'::public.submission_status) OR (submitted_by_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.user_id = auth.uid()) AND (profiles.role = ANY (ARRAY['Admin'::public.users_roles, 'Database Manager'::public.users_roles])))))));


CREATE TRIGGER notify_discord_new_cube AFTER INSERT OR UPDATE ON public.cube_models FOR EACH ROW EXECUTE FUNCTION public.notify_discord_new_cube_model();
ALTER TABLE "public"."cube_models" DISABLE TRIGGER "notify_discord_new_cube";

CREATE TRIGGER trg_price_alert_discord AFTER INSERT ON public.cube_vendor_links_snapshot FOR EACH ROW EXECUTE FUNCTION public.notify_discord_price_alert();
ALTER TABLE "public"."cube_vendor_links_snapshot" DISABLE TRIGGER "trg_price_alert_discord";

CREATE TRIGGER notify_discord_new_user AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.notify_discord_new_user();
ALTER TABLE "public"."profiles" DISABLE TRIGGER "notify_discord_new_user";

CREATE TRIGGER notify_discord_new_user_report AFTER INSERT ON public.reports FOR EACH ROW EXECUTE FUNCTION public.notify_discord_new_user_report();
ALTER TABLE "public"."reports" DISABLE TRIGGER "notify_discord_new_user_report";

drop policy "Everyone can select avatars 1oj01fe_0" on "storage"."objects";

drop policy "Everyone can select banners 1tghu4n_0" on "storage"."objects";


  create policy "Users can delete vendor images"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'vendors-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can upload vendor images"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'vendors-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



