create type "public"."cube_review_status" as enum ('published', 'draft', 'hidden');


  create table "public"."helpful_review" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "review_id" bigint not null,
    "user_id" uuid not null
      );


alter table "public"."helpful_review" enable row level security;


  create table "public"."user_cube_reviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "review" text not null,
    "status" public.cube_review_status not null default 'draft'::public.cube_review_status,
    "user_id" uuid not null,
    "cube" text not null,
    "title" text not null,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."user_cube_reviews" enable row level security;


  create table "public"."user_cube_reviews_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "slug" text not null,
    "label" text not null,
    "active" boolean not null default true
      );


alter table "public"."user_cube_reviews_categories" enable row level security;


  create table "public"."user_cube_reviews_ratings" (
    "created_at" timestamp with time zone not null default now(),
    "review_id" bigint not null,
    "category_id" bigint not null,
    "rating" real not null
      );


alter table "public"."user_cube_reviews_ratings" enable row level security;

CREATE UNIQUE INDEX cube_reviews_pkey ON public.user_cube_reviews USING btree (id);

CREATE UNIQUE INDEX helpful_review_pkey ON public.helpful_review USING btree (id);

CREATE UNIQUE INDEX single_helpful_per_user_per_review ON public.helpful_review USING btree (user_id, review_id);

CREATE UNIQUE INDEX single_review_per_user_per_cube ON public.user_cube_reviews USING btree (cube, user_id);

CREATE UNIQUE INDEX user_cube_reviews_categories_pkey ON public.user_cube_reviews_categories USING btree (id);

CREATE UNIQUE INDEX user_cube_reviews_ratings_pkey ON public.user_cube_reviews_ratings USING btree (review_id, category_id);

alter table "public"."helpful_review" add constraint "helpful_review_pkey" PRIMARY KEY using index "helpful_review_pkey";

alter table "public"."user_cube_reviews" add constraint "cube_reviews_pkey" PRIMARY KEY using index "cube_reviews_pkey";

alter table "public"."user_cube_reviews_categories" add constraint "user_cube_reviews_categories_pkey" PRIMARY KEY using index "user_cube_reviews_categories_pkey";

alter table "public"."user_cube_reviews_ratings" add constraint "user_cube_reviews_ratings_pkey" PRIMARY KEY using index "user_cube_reviews_ratings_pkey";

alter table "public"."helpful_review" add constraint "helpful_review_review_id_fkey" FOREIGN KEY (review_id) REFERENCES public.user_cube_reviews(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."helpful_review" validate constraint "helpful_review_review_id_fkey";

alter table "public"."helpful_review" add constraint "helpful_review_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."helpful_review" validate constraint "helpful_review_user_id_fkey";

alter table "public"."user_cube_reviews" add constraint "user_cube_reviews_cube_fkey" FOREIGN KEY (cube) REFERENCES public.cube_models(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_cube_reviews" validate constraint "user_cube_reviews_cube_fkey";

alter table "public"."user_cube_reviews" add constraint "user_cube_reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_cube_reviews" validate constraint "user_cube_reviews_user_id_fkey";

alter table "public"."user_cube_reviews_ratings" add constraint "user_cube_reviews_ratings_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.user_cube_reviews_categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_cube_reviews_ratings" validate constraint "user_cube_reviews_ratings_category_id_fkey";

alter table "public"."user_cube_reviews_ratings" add constraint "user_cube_reviews_ratings_rating_check" CHECK (((rating >= (0.5)::double precision) AND (rating <= (5)::double precision))) not valid;

alter table "public"."user_cube_reviews_ratings" validate constraint "user_cube_reviews_ratings_rating_check";

alter table "public"."user_cube_reviews_ratings" add constraint "user_cube_reviews_ratings_review_id_fkey" FOREIGN KEY (review_id) REFERENCES public.user_cube_reviews(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_cube_reviews_ratings" validate constraint "user_cube_reviews_ratings_review_id_fkey";

create or replace view "public"."v_detailed_user_cube_reviews" as  WITH ratings AS (
         SELECT ucrr.review_id,
            jsonb_object_agg(ucrc.label, ucrr.rating) AS ratings
           FROM (public.user_cube_reviews_ratings ucrr
             JOIN public.user_cube_reviews_categories ucrc ON (((ucrc.id = ucrr.category_id) AND (ucrc.active = true))))
          GROUP BY ucrr.review_id
        ), helpful AS (
         SELECT hr.review_id,
            count(DISTINCT hr.user_id) AS helpful_count
           FROM public.helpful_review hr
          GROUP BY hr.review_id
        )
 SELECT ucr.id,
    ucr.created_at,
    ucr.review,
    ucr.status,
    ucr.user_id,
    ucr.cube,
    ucr.title,
    ucr.updated_at,
    COALESCE(r.ratings, '{}'::jsonb) AS ratings,
    COALESCE(h.helpful_count, (0)::bigint) AS helpful_count
   FROM ((public.user_cube_reviews ucr
     LEFT JOIN ratings r ON ((r.review_id = ucr.id)))
     LEFT JOIN helpful h ON ((h.review_id = ucr.id)));


grant delete on table "public"."helpful_review" to "anon";

grant insert on table "public"."helpful_review" to "anon";

grant references on table "public"."helpful_review" to "anon";

grant select on table "public"."helpful_review" to "anon";

grant trigger on table "public"."helpful_review" to "anon";

grant truncate on table "public"."helpful_review" to "anon";

grant update on table "public"."helpful_review" to "anon";

grant delete on table "public"."helpful_review" to "authenticated";

grant insert on table "public"."helpful_review" to "authenticated";

grant references on table "public"."helpful_review" to "authenticated";

grant select on table "public"."helpful_review" to "authenticated";

grant trigger on table "public"."helpful_review" to "authenticated";

grant truncate on table "public"."helpful_review" to "authenticated";

grant update on table "public"."helpful_review" to "authenticated";

grant delete on table "public"."helpful_review" to "postgres";

grant insert on table "public"."helpful_review" to "postgres";

grant references on table "public"."helpful_review" to "postgres";

grant select on table "public"."helpful_review" to "postgres";

grant trigger on table "public"."helpful_review" to "postgres";

grant truncate on table "public"."helpful_review" to "postgres";

grant update on table "public"."helpful_review" to "postgres";

grant delete on table "public"."helpful_review" to "service_role";

grant insert on table "public"."helpful_review" to "service_role";

grant references on table "public"."helpful_review" to "service_role";

grant select on table "public"."helpful_review" to "service_role";

grant trigger on table "public"."helpful_review" to "service_role";

grant truncate on table "public"."helpful_review" to "service_role";

grant update on table "public"."helpful_review" to "service_role";

grant delete on table "public"."user_cube_reviews" to "anon";

grant insert on table "public"."user_cube_reviews" to "anon";

grant references on table "public"."user_cube_reviews" to "anon";

grant select on table "public"."user_cube_reviews" to "anon";

grant trigger on table "public"."user_cube_reviews" to "anon";

grant truncate on table "public"."user_cube_reviews" to "anon";

grant update on table "public"."user_cube_reviews" to "anon";

grant delete on table "public"."user_cube_reviews" to "authenticated";

grant insert on table "public"."user_cube_reviews" to "authenticated";

grant references on table "public"."user_cube_reviews" to "authenticated";

grant select on table "public"."user_cube_reviews" to "authenticated";

grant trigger on table "public"."user_cube_reviews" to "authenticated";

grant truncate on table "public"."user_cube_reviews" to "authenticated";

grant update on table "public"."user_cube_reviews" to "authenticated";

grant delete on table "public"."user_cube_reviews" to "postgres";

grant insert on table "public"."user_cube_reviews" to "postgres";

grant references on table "public"."user_cube_reviews" to "postgres";

grant select on table "public"."user_cube_reviews" to "postgres";

grant trigger on table "public"."user_cube_reviews" to "postgres";

grant truncate on table "public"."user_cube_reviews" to "postgres";

grant update on table "public"."user_cube_reviews" to "postgres";

grant delete on table "public"."user_cube_reviews" to "service_role";

grant insert on table "public"."user_cube_reviews" to "service_role";

grant references on table "public"."user_cube_reviews" to "service_role";

grant select on table "public"."user_cube_reviews" to "service_role";

grant trigger on table "public"."user_cube_reviews" to "service_role";

grant truncate on table "public"."user_cube_reviews" to "service_role";

grant update on table "public"."user_cube_reviews" to "service_role";

grant delete on table "public"."user_cube_reviews_categories" to "anon";

grant insert on table "public"."user_cube_reviews_categories" to "anon";

grant references on table "public"."user_cube_reviews_categories" to "anon";

grant select on table "public"."user_cube_reviews_categories" to "anon";

grant trigger on table "public"."user_cube_reviews_categories" to "anon";

grant truncate on table "public"."user_cube_reviews_categories" to "anon";

grant update on table "public"."user_cube_reviews_categories" to "anon";

grant delete on table "public"."user_cube_reviews_categories" to "authenticated";

grant insert on table "public"."user_cube_reviews_categories" to "authenticated";

grant references on table "public"."user_cube_reviews_categories" to "authenticated";

grant select on table "public"."user_cube_reviews_categories" to "authenticated";

grant trigger on table "public"."user_cube_reviews_categories" to "authenticated";

grant truncate on table "public"."user_cube_reviews_categories" to "authenticated";

grant update on table "public"."user_cube_reviews_categories" to "authenticated";

grant delete on table "public"."user_cube_reviews_categories" to "postgres";

grant insert on table "public"."user_cube_reviews_categories" to "postgres";

grant references on table "public"."user_cube_reviews_categories" to "postgres";

grant select on table "public"."user_cube_reviews_categories" to "postgres";

grant trigger on table "public"."user_cube_reviews_categories" to "postgres";

grant truncate on table "public"."user_cube_reviews_categories" to "postgres";

grant update on table "public"."user_cube_reviews_categories" to "postgres";

grant delete on table "public"."user_cube_reviews_categories" to "service_role";

grant insert on table "public"."user_cube_reviews_categories" to "service_role";

grant references on table "public"."user_cube_reviews_categories" to "service_role";

grant select on table "public"."user_cube_reviews_categories" to "service_role";

grant trigger on table "public"."user_cube_reviews_categories" to "service_role";

grant truncate on table "public"."user_cube_reviews_categories" to "service_role";

grant update on table "public"."user_cube_reviews_categories" to "service_role";

grant delete on table "public"."user_cube_reviews_ratings" to "anon";

grant insert on table "public"."user_cube_reviews_ratings" to "anon";

grant references on table "public"."user_cube_reviews_ratings" to "anon";

grant select on table "public"."user_cube_reviews_ratings" to "anon";

grant trigger on table "public"."user_cube_reviews_ratings" to "anon";

grant truncate on table "public"."user_cube_reviews_ratings" to "anon";

grant update on table "public"."user_cube_reviews_ratings" to "anon";

grant delete on table "public"."user_cube_reviews_ratings" to "authenticated";

grant insert on table "public"."user_cube_reviews_ratings" to "authenticated";

grant references on table "public"."user_cube_reviews_ratings" to "authenticated";

grant select on table "public"."user_cube_reviews_ratings" to "authenticated";

grant trigger on table "public"."user_cube_reviews_ratings" to "authenticated";

grant truncate on table "public"."user_cube_reviews_ratings" to "authenticated";

grant update on table "public"."user_cube_reviews_ratings" to "authenticated";

grant delete on table "public"."user_cube_reviews_ratings" to "postgres";

grant insert on table "public"."user_cube_reviews_ratings" to "postgres";

grant references on table "public"."user_cube_reviews_ratings" to "postgres";

grant select on table "public"."user_cube_reviews_ratings" to "postgres";

grant trigger on table "public"."user_cube_reviews_ratings" to "postgres";

grant truncate on table "public"."user_cube_reviews_ratings" to "postgres";

grant update on table "public"."user_cube_reviews_ratings" to "postgres";

grant delete on table "public"."user_cube_reviews_ratings" to "service_role";

grant insert on table "public"."user_cube_reviews_ratings" to "service_role";

grant references on table "public"."user_cube_reviews_ratings" to "service_role";

grant select on table "public"."user_cube_reviews_ratings" to "service_role";

grant trigger on table "public"."user_cube_reviews_ratings" to "service_role";

grant truncate on table "public"."user_cube_reviews_ratings" to "service_role";

grant update on table "public"."user_cube_reviews_ratings" to "service_role";


  create policy "Enable delete for users based on user_id"
  on "public"."helpful_review"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."helpful_review"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."helpful_review"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for users based on user_id"
  on "public"."user_cube_reviews"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."user_cube_reviews"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users based on user_id"
  on "public"."user_cube_reviews"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id))
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."user_cube_reviews_categories"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."user_cube_reviews_ratings"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."user_cube_reviews_ratings"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users own reviews ratings"
  on "public"."user_cube_reviews_ratings"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_cube_reviews ucr
  WHERE ((ucr.id = user_cube_reviews_ratings.review_id) AND (ucr.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.user_cube_reviews ucr
  WHERE ((ucr.id = user_cube_reviews_ratings.review_id) AND (ucr.user_id = auth.uid())))));



