create type "public"."date_precision" as enum ('day', 'month', 'year');

drop trigger if exists "log_cube_models" on "public"."cube_models";

drop trigger if exists "trg_cube_models_table_rules" on "public"."cube_models";

drop trigger if exists "notify_discord_new_cube" on "public"."cube_models";

drop policy "Enable delete for Admins and Community Managers" on "public"."cube_models";

drop policy "Only Database Manager's and Admin's can insert" on "public"."cube_models";

drop view if exists "public"."v_awards_category_winners";

drop view if exists "public"."v_detailed_cube_models";

drop view if exists "public"."v_user_stats";

alter table "public"."cube_models"
drop constraint "cube_models_related_to_fkey";

alter table "public"."user_cubes"
drop constraint "user_cubes_cube_fkey";

alter table "public"."cubes_model_features"
drop constraint "cubes_model_features_cube_fkey";

alter table "public"."user_cube_ratings"
drop constraint "user_ratings_cube_slug_fkey";

alter table "public"."cube_vendor_links_snapshot"
drop constraint "cube_vendor_links_snapshot_cube_slug_fkey";

alter table "public"."cube_vendor_links"
drop constraint "cube_vendor_links_duplicate_cube_slug_fkey";

alter table "public"."user_cube_reviews"
drop constraint "user_cube_reviews_cube_fkey";

alter table "public"."cube_models" drop constraint "cubes_pkey";

drop index if exists "public"."cubes_pkey";

alter table "public"."cube_models" alter column "version_type" drop default;

alter type "public"."cube_surface_finish" rename to "cube_surface_finish__old_version_to_be_dropped";

create type "public"."cube_surface_finish" as enum ('Frosted', 'UV Coated', 'Glossy', 'Sculpted');

alter type "public"."cube_version_type" rename to "cube_version_type__old_version_to_be_dropped";

create type "public"."cube_version_type" as enum ('Base', 'Variant', 'Limited');


  create table "public"."cube_series" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
      );


alter table "public"."cube_series" enable row level security;

alter table "public"."cube_models" alter column sub_type type "public"."cubes_subtypes" using sub_type::text::"public"."cubes_subtypes";

alter table "public"."cube_models" alter column version_type type "public"."cube_version_type" using (
    case version_type::text
        when 'Trim' then 'Variant'
        else version_type::text
    end
)::"public"."cube_version_type";

alter table "public"."cube_models" alter column "version_type" set default 'Base'::public.cube_version_type;

drop type "public"."cube_surface_finish__old_version_to_be_dropped";

drop type "public"."cube_version_type__old_version_to_be_dropped";

alter table "public"."cube_models" drop column "notes";

alter table "public"."cube_models" drop column "rating";

alter table "public"."cube_models" drop column "status";

-- Populate cube_models' brand_id before deleting the brand column

alter table "public"."cube_models" add column "brand_id" bigint;

update cube_models cm
set brand_id = (select id from brands b where b.name = cm.brand);

alter table "public"."cube_models" alter column "brand_id" set not null;

alter table "public"."cube_models" drop column "brand";

-- End

-- Populate cube_models' name column

alter table "public"."cube_models" add column "name" text;

update cube_models
set name = trim(concat(series, ' ', model, ' ', version_name));

alter table "public"."cube_models" alter column "name" set not null;

alter table "public"."cube_models" drop column "version_name";

alter table "public"."cube_models" drop column "model";

alter table "public"."cube_models" drop column "series";

-- End

alter table "public"."cube_models" add column "release_date_precision" public.date_precision;

alter table "public"."cube_models" add column "series_id" bigint;

-- Populate cube_models' type_id column

alter table "public"."cube_models" add column "type_id" bigint;

update cube_models cm
set type_id = coalesce(
	(
		select ct.id
		from public.cube_types ct
		where ct.name = cm.type
	),
	(
		select ct.id
		from public.cube_types ct
		where ct.name = 'Other'
	)
);

alter table "public"."cube_models" alter column "type_id" set not null;

alter table "public"."cube_models" drop column "type";

-- End

update cube_models
set sub_type = 'Other'::cubes_subtypes
where sub_type is null;

alter table "public"."cube_models" alter column "sub_type" set not null;

alter table "public"."cube_models" alter column "submitted_by_id" drop default;

alter table "public"."cube_models" alter column "surface_finish" set data type public.cube_surface_finish using "surface_finish"::text::public.cube_surface_finish;

alter table "public"."cube_models" alter column "verified_by_id" drop default;

alter table "public"."cube_models" alter column "weight" drop not null;

drop type "public"."cube_surface_finishes";

CREATE UNIQUE INDEX cube_models_pkey ON public.cube_models USING btree (id);

CREATE UNIQUE INDEX cube_series_name_key ON public.cube_series USING btree (name);

CREATE UNIQUE INDEX cube_series_pkey ON public.cube_series USING btree (id);

alter table "public"."cube_models" add constraint "cube_models_pkey" PRIMARY KEY using index "cube_models_pkey";

ALTER TABLE ONLY "public"."cube_models"
    ADD CONSTRAINT "cube_models_related_to_fkey" FOREIGN KEY ("related_to") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."user_cubes"
    ADD CONSTRAINT "user_cubes_cube_fkey" FOREIGN KEY ("cube") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."cubes_model_features"
    ADD CONSTRAINT "cubes_model_features_cube_fkey" FOREIGN KEY ("cube") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_cube_ratings"
ADD CONSTRAINT "user_ratings_cube_slug_fkey" FOREIGN KEY ("cube_slug") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

alter table public.cube_vendor_links
disable trigger "trg_cube_links_table_rules";

delete from public.cube_vendor_links cvl
where not exists (
	select 1
	from public.cube_models cm
	where cm.slug = cvl.cube_slug
);

alter table public.cube_vendor_links
enable trigger "trg_cube_links_table_rules";

ALTER TABLE ONLY "public"."cube_vendor_links"
    ADD CONSTRAINT "cube_vendor_links_duplicate_cube_slug_fkey" FOREIGN KEY ("cube_slug") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_cube_reviews"
    ADD CONSTRAINT "user_cube_reviews_cube_fkey" FOREIGN KEY ("cube") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

delete from public.cube_vendor_links_snapshot cvs
where not exists (
	select 1
	from public.cube_models cm
	where cm.slug = cvs.cube_slug
);

ALTER TABLE ONLY "public"."cube_vendor_links_snapshot"
    ADD CONSTRAINT "cube_vendor_links_snapshot_cube_slug_fkey" FOREIGN KEY ("cube_slug") REFERENCES "public"."cube_models"("slug") ON UPDATE CASCADE ON DELETE CASCADE;

alter table "public"."cube_series" add constraint "cube_series_pkey" PRIMARY KEY using index "cube_series_pkey";

alter table "public"."cube_models" add constraint "cube_models_brand_id_fkey" FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."cube_models" validate constraint "cube_models_brand_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_series_id_fkey" FOREIGN KEY (series_id) REFERENCES public.cube_series(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."cube_models" validate constraint "cube_models_series_id_fkey";

alter table "public"."cube_models" add constraint "cube_models_type_id_fkey" FOREIGN KEY (type_id) REFERENCES public.cube_types(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."cube_models" validate constraint "cube_models_type_id_fkey";

update cube_models
set release_date_precision = 'day'::public.date_precision
where release_date is not null;

alter table "public"."cube_models" add constraint "release_date_precision_check" CHECK (((release_date IS NULL) = (release_date_precision IS NULL))) not valid;

alter table "public"."cube_models" validate constraint "release_date_precision_check";

alter table "public"."cube_series" add constraint "cube_series_name_key" UNIQUE using index "cube_series_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.cube_models_table_rules()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$begin

if new.submitted_by_id is distinct from old.submitted_by_id
and tg_op = 'UPDATE' then raise exception 'Cannot change submitted_by_id';

end if;

if new.id is distinct from old.id
and tg_op = 'UPDATE' then raise exception 'Cannot change id';

end if;

if new.created_at is distinct from old.created_at
and tg_op = 'UPDATE' then raise exception 'Cannot change created_at';

end if;

if tg_op = 'DELETE' then return old;

else return new;

end if;

end;$function$
;

create or replace view "public"."v_awards_category_winners" with (security_invoker = on) as  WITH votes AS (
         SELECT an.category_id,
            cm.slug AS nominee_slug,
            count(DISTINCT auv.user_id) AS vote_count
           FROM ((public.awards_nominee an
             JOIN public.cube_models cm ON ((cm.id = an.cube_id)))
             LEFT JOIN public.awards_user_vote auv ON ((auv.nominee_id = an.id)))
          GROUP BY an.category_id, cm.slug
        ), ranked AS (
         SELECT v.category_id,
            v.nominee_slug,
            v.vote_count,
            dense_rank() OVER (PARTITION BY v.category_id ORDER BY v.vote_count DESC) AS rnk
           FROM votes v
        )
 SELECT r.category_id,
    r.nominee_slug,
    r.vote_count,
    ( SELECT count(*) AS count
           FROM public.awards_nominee an
          WHERE (an.category_id = r.category_id)) AS nominee_count
   FROM ranked r
  WHERE (r.rnk = 1);


create or replace view "public"."v_detailed_cube_models" with (security_invoker = on) as  SELECT cm.name,
    cm.image_url,
    v.name AS image_source,
    cm.slug,
    cm.created_at,
    cm.updated_at,
    cm.discontinued,
    cm.release_date,
    cm.id,
    cm.sub_type,
    cm.weight,
    cm.related_to,
    cm.version_type,
    cm.surface_finish,
    cm.verified_at,
    cm.size,
    cm.submitted_by_id,
    cm.verified_by_id,
    ( SELECT b.name
           FROM public.brands b
          WHERE (b.id = cm.brand_id)) AS brand,
    ( SELECT ct.name
           FROM public.cube_types ct
          WHERE (ct.id = cm.type_id)) AS type,
    ( SELECT cs.name
           FROM public.cube_series cs
          WHERE (cs.id = cm.series_id)) AS series,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'ball_core'::text)))) AS ball_core,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'maglev'::text)))) AS maglev,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'magnetic'::text)))) AS magnetic,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'modded'::text)))) AS modded,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'smart'::text)))) AS smart,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'stickered'::text)))) AS stickered,
    (EXISTS ( SELECT 1
           FROM public.cubes_model_features f
          WHERE ((f.cube = cm.slug) AND (f.feature = 'wca_legal'::text)))) AS wca_legal,
    (EXTRACT(year FROM cm.release_date))::integer AS year,
    ( SELECT count(*) AS count
           FROM public.user_cubes uc
          WHERE (uc.cube = cm.slug)) AS popularity,
    ( SELECT avg(cvl.price) AS avg
           FROM public.cube_vendor_links cvl
          WHERE ((cvl.cube_slug = cm.slug) AND (( SELECT v_1.currency
                   FROM public.vendors v_1
                  WHERE (cvl.vendor_name = v_1.name)) = 'USD'::public.currencies))) AS avg_price,
    ( SELECT min(cvl.price) AS min
           FROM public.cube_vendor_links cvl
          WHERE ((cvl.cube_slug = cm.slug) AND (( SELECT v_1.currency
                   FROM public.vendors v_1
                  WHERE (cvl.vendor_name = v_1.name)) = 'USD'::public.currencies))) AS low_price,
    ( SELECT avg(ucr.rating) AS avg
           FROM public.user_cube_ratings ucr
          WHERE (ucr.cube_slug = cm.slug)) AS rating,
    ( SELECT count(ucr.rating) AS count
           FROM public.user_cube_ratings ucr
          WHERE (ucr.cube_slug = cm.slug)) AS rating_count
   FROM (public.cube_models cm
     LEFT JOIN public.vendors v ON ((lower(regexp_replace(split_part(regexp_replace(cm.image_url, '^https?://'::text, ''::text), '/'::text, 1), '^www\.'::text, ''::text)) = lower(regexp_replace(split_part(regexp_replace(v.base_url, '^https?://'::text, ''::text), '/'::text, 1), '^www\.'::text, ''::text)))));


create or replace view "public"."v_user_stats" with (security_invoker = on) as  WITH cube_stats AS (
         SELECT uc.user_id,
            count(*) AS cube_count,
            sum(uc.purchase_price) AS collection_value
           FROM public.user_cubes uc
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY uc.user_id
        ), rating_stats AS (
         SELECT user_cube_ratings.user_id,
            avg(user_cube_ratings.rating) AS rating_avg,
            count(*) AS rating_count
           FROM public.user_cube_ratings
          GROUP BY user_cube_ratings.user_id
        ), brand_counts AS (
         SELECT uc.user_id,
            b.name AS brand,
            count(*) AS cnt
           FROM ((public.user_cubes uc
             JOIN public.cube_models cm ON ((cm.slug = uc.cube)))
             JOIN public.brands b ON ((b.id = cm.brand_id)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY b.name, uc.user_id
        ), type_counts AS (
         SELECT uc.user_id,
            ct_1.name AS type,
            count(*) AS cnt
           FROM ((public.user_cubes uc
             JOIN public.cube_models cm ON ((cm.slug = uc.cube)))
             JOIN public.cube_types ct_1 ON ((ct_1.id = cm.type_id)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY ct_1.name, uc.user_id
        ), store_counts AS (
         SELECT uc.user_id,
            v.name AS store,
            count(*) AS cnt
           FROM (public.user_cubes uc
             JOIN public.vendors v ON ((v.slug = uc.bought_from)))
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY v.name, uc.user_id
        ), condition_counts AS (
         SELECT uc.user_id,
            uc.condition,
            count(*) AS cnt
           FROM public.user_cubes uc
          WHERE (uc.status <> 'Wishlist'::public.user_cube_status)
          GROUP BY uc.condition, uc.user_id
        ), cubes_over_time_counts AS (
         SELECT user_cubes.user_id,
            (date_trunc('month'::text, (user_cubes.acquired_at)::timestamp with time zone))::date AS month,
            count(*) AS cnt
           FROM public.user_cubes
          WHERE ((user_cubes.acquired_at IS NOT NULL) AND (user_cubes.status <> 'Wishlist'::public.user_cube_status))
          GROUP BY user_cubes.user_id, ((date_trunc('month'::text, (user_cubes.acquired_at)::timestamp with time zone))::date)
        ), brand_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.brand
                    ELSE 'Other'::text
                END AS brand,
            sum(t.cnt) AS cnt
           FROM ( SELECT brand_counts.user_id,
                    brand_counts.brand,
                    brand_counts.cnt,
                    row_number() OVER (PARTITION BY brand_counts.user_id ORDER BY brand_counts.cnt DESC) AS rn
                   FROM brand_counts
                  WHERE (brand_counts.brand IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.brand
                    ELSE 'Other'::text
                END
        ), store_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.store
                    ELSE 'Other'::text
                END AS store,
            sum(t.cnt) AS cnt
           FROM ( SELECT store_counts.user_id,
                    store_counts.store,
                    store_counts.cnt,
                    row_number() OVER (PARTITION BY store_counts.user_id ORDER BY store_counts.cnt DESC) AS rn
                   FROM store_counts
                  WHERE (store_counts.store IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.store
                    ELSE 'Other'::text
                END
        ), type_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.type
                    ELSE 'Other'::text
                END AS type,
            sum(t.cnt) AS cnt
           FROM ( SELECT type_counts.user_id,
                    type_counts.type,
                    type_counts.cnt,
                    row_number() OVER (PARTITION BY type_counts.user_id ORDER BY type_counts.cnt DESC) AS rn
                   FROM type_counts
                  WHERE (type_counts.type IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN t.type
                    ELSE 'Other'::text
                END
        ), condition_grouped AS (
         SELECT t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN (t.condition)::text
                    ELSE 'Other'::text
                END AS condition,
            sum(t.cnt) AS cnt
           FROM ( SELECT condition_counts.user_id,
                    condition_counts.condition,
                    condition_counts.cnt,
                    row_number() OVER (PARTITION BY condition_counts.user_id ORDER BY condition_counts.cnt DESC) AS rn
                   FROM condition_counts
                  WHERE (condition_counts.condition IS NOT NULL)) t
          GROUP BY t.user_id,
                CASE
                    WHEN (t.rn <= 7) THEN (t.condition)::text
                    ELSE 'Other'::text
                END
        ), cubes_per_brand AS (
         SELECT brand_grouped.user_id,
            COALESCE(jsonb_object_agg(brand_grouped.brand, brand_grouped.cnt) FILTER (WHERE (brand_grouped.brand IS NOT NULL)), '{}'::jsonb) AS cubes_per_brand
           FROM brand_grouped
          GROUP BY brand_grouped.user_id
        ), cubes_per_store AS (
         SELECT store_grouped.user_id,
            COALESCE(jsonb_object_agg(store_grouped.store, store_grouped.cnt) FILTER (WHERE (store_grouped.store IS NOT NULL)), '{}'::jsonb) AS cubes_per_store
           FROM store_grouped
          GROUP BY store_grouped.user_id
        ), cubes_per_type AS (
         SELECT type_grouped.user_id,
            COALESCE(jsonb_object_agg(type_grouped.type, type_grouped.cnt) FILTER (WHERE (type_grouped.type IS NOT NULL)), '{}'::jsonb) AS cubes_per_type
           FROM type_grouped
          GROUP BY type_grouped.user_id
        ), cubes_per_condition AS (
         SELECT condition_grouped.user_id,
            COALESCE(jsonb_object_agg(condition_grouped.condition, condition_grouped.cnt) FILTER (WHERE (condition_grouped.condition IS NOT NULL)), '{}'::jsonb) AS cubes_per_condition
           FROM condition_grouped
          GROUP BY condition_grouped.user_id
        ), cubes_over_time AS (
         SELECT cubes_over_time_counts.user_id,
            COALESCE(jsonb_object_agg(to_char((cubes_over_time_counts.month)::timestamp with time zone, 'YYYY-MM'::text), cubes_over_time_counts.cnt ORDER BY cubes_over_time_counts.month), '{}'::jsonb) AS cubes_over_time
           FROM cubes_over_time_counts
          GROUP BY cubes_over_time_counts.user_id
        )
 SELECT cs.user_id,
    cs.cube_count,
    cs.collection_value,
    rs.rating_count,
    rs.rating_avg,
    cb.cubes_per_brand,
    cps.cubes_per_store,
    cot.cubes_over_time,
    ct.cubes_per_type,
    cp.cubes_per_condition
   FROM ((((((cube_stats cs
     LEFT JOIN rating_stats rs ON ((rs.user_id = cs.user_id)))
     LEFT JOIN cubes_per_brand cb ON ((cb.user_id = cs.user_id)))
     LEFT JOIN cubes_per_store cps ON ((cps.user_id = cs.user_id)))
     LEFT JOIN cubes_over_time cot ON ((cot.user_id = cs.user_id)))
     LEFT JOIN cubes_per_type ct ON ((ct.user_id = cs.user_id)))
     LEFT JOIN cubes_per_condition cp ON ((cp.user_id = cs.user_id)));


grant delete on table "public"."cube_series" to "anon";

grant insert on table "public"."cube_series" to "anon";

grant references on table "public"."cube_series" to "anon";

grant select on table "public"."cube_series" to "anon";

grant trigger on table "public"."cube_series" to "anon";

grant truncate on table "public"."cube_series" to "anon";

grant update on table "public"."cube_series" to "anon";

grant delete on table "public"."cube_series" to "authenticated";

grant insert on table "public"."cube_series" to "authenticated";

grant references on table "public"."cube_series" to "authenticated";

grant select on table "public"."cube_series" to "authenticated";

grant trigger on table "public"."cube_series" to "authenticated";

grant truncate on table "public"."cube_series" to "authenticated";

grant update on table "public"."cube_series" to "authenticated";

grant delete on table "public"."cube_series" to "service_role";

grant insert on table "public"."cube_series" to "service_role";

grant references on table "public"."cube_series" to "service_role";

grant select on table "public"."cube_series" to "service_role";

grant trigger on table "public"."cube_series" to "service_role";

grant truncate on table "public"."cube_series" to "service_role";

grant update on table "public"."cube_series" to "service_role";

CREATE TRIGGER notify_discord_new_cube AFTER INSERT ON public.cube_models FOR EACH ROW EXECUTE FUNCTION public.notify_discord_new_cube_model();

CREATE TRIGGER "trg_cube_models_table_rules" BEFORE INSERT OR DELETE OR UPDATE ON "public"."cube_models" FOR EACH ROW EXECUTE FUNCTION "public"."cube_models_table_rules"();

CREATE TRIGGER log_cube_models AFTER UPDATE OR DELETE OR INSERT ON public.cube_models FOR EACH ROW EXECUTE FUNCTION public.log_data_changes();
